In [179]:
import pandas as pd
import datetime

In [180]:
ec = pd.read_excel('contratos.gov.xlsx', header=1, decimal=',', thousands='.')
display(ec.head())
ec.info()

,Número do instrumento,Fornecedor,Vig. Início,Vig. Fim,Valor Global,Núm. Parcelas,Valor Parcela,Atualizado em,Data Encerramento
0,00002/2022,16.563.763/0001-80 - RF CLIMATIZACAO COMERCIO ...,01/03/2022,01/03/2027,"R$ 32.782,62",12,"R$ 2.731,89",15/04/2026 16:51,NaN
1,00002/2023,96.707.088/0001-55 - RCB DE OLIVEIRA & OLIVEIR...,21/02/2023,21/02/2027,"R$ 91.030,42",12,"R$ 7.585,87",15/04/2026 16:31,NaN
2,00017/2025,13.504.675/0001-10 - EMPRESA BAIANA DE AGUAS E...,10/11/2025,Indeterminado,"R$ 19.224,64",Indeterminado,"R$ 19.224,64",15/04/2026 15:52,NaN
3,00009/2025,15.139.629/0001-94 - COMPANHIA DE ELETRICIDADE...,16/06/2025,Indeterminado,"R$ 563.133,96",Indeterminado,"R$ 563.133,96",15/04/2026 15:26,NaN
4,00033/2024,32.996.276/0001-68 - ENTHEOS SERVICOS LTDA,04/09/2024,04/09/2026,"R$ 301.377,60",12,"R$ 25.114,80",15/04/2026 15:03,NaN

<class 'pandas.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Número do instrumento  147 non-null    str
 1   Fornecedor             147 non-null    str
 2   Vig. Início            147 non-null    str
 3   Vig. Fim               147 non-null    str
 4   Valor Global           147 non-null    str
 5   Núm. Parcelas          147 non-null    object
 6   Valor Parcela          147 non-null    str
 7   Atualizado em          147 non-null    str
 8   Data Encerramento      0 non-null      float64
dtypes: float64(1), object(1), str(7)
memory usage: 10.5+ KB

In [181]:
# droop colunas que não são necessárias
ec.drop(columns=['Fornecedor', 'Atualizado em', 'Data Encerramento'], inplace=True)

display(ec.head())
ec.info()

,Número do instrumento,Vig. Início,Vig. Fim,Valor Global,Núm. Parcelas,Valor Parcela
0,00002/2022,01/03/2022,01/03/2027,"R$ 32.782,62",12,"R$ 2.731,89"
1,00002/2023,21/02/2023,21/02/2027,"R$ 91.030,42",12,"R$ 7.585,87"
2,00017/2025,10/11/2025,Indeterminado,"R$ 19.224,64",Indeterminado,"R$ 19.224,64"
3,00009/2025,16/06/2025,Indeterminado,"R$ 563.133,96",Indeterminado,"R$ 563.133,96"
4,00033/2024,04/09/2024,04/09/2026,"R$ 301.377,60",12,"R$ 25.114,80"

<class 'pandas.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Número do instrumento  147 non-null    str
 1   Vig. Início            147 non-null    str
 2   Vig. Fim               147 non-null    str
 3   Valor Global           147 non-null    str
 4   Núm. Parcelas          147 non-null    object
 5   Valor Parcela          147 non-null    str
dtypes: object(1), str(5)
memory usage: 7.0+ KB

In [182]:
# mudar nome das colunas
ec.rename(columns={'Número do instrumento': 'numero_instrumento',
                   'Vig. Início': 'vigencia_inicio',
                   'Vig. Fim': 'vigencia_fim',
                   'Valor Global': 'valor_global',
                   'Núm. Parcelas': 'numero_parcelas',
                   'Valor Parcela': 'valor_parcela'}, inplace=True)

display(ec.head())
ec.info()

,numero_instrumento,vigencia_inicio,vigencia_fim,valor_global,numero_parcelas,valor_parcela
0,00002/2022,01/03/2022,01/03/2027,"R$ 32.782,62",12,"R$ 2.731,89"
1,00002/2023,21/02/2023,21/02/2027,"R$ 91.030,42",12,"R$ 7.585,87"
2,00017/2025,10/11/2025,Indeterminado,"R$ 19.224,64",Indeterminado,"R$ 19.224,64"
3,00009/2025,16/06/2025,Indeterminado,"R$ 563.133,96",Indeterminado,"R$ 563.133,96"
4,00033/2024,04/09/2024,04/09/2026,"R$ 301.377,60",12,"R$ 25.114,80"

<class 'pandas.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   numero_instrumento  147 non-null    str
 1   vigencia_inicio     147 non-null    str
 2   vigencia_fim        147 non-null    str
 3   valor_global        147 non-null    str
 4   numero_parcelas     147 non-null    object
 5   valor_parcela       147 non-null    str
dtypes: object(1), str(5)
memory usage: 7.0+ KB

In [183]:
# trocar "Indeterminado" por data na coluna "vigencia_fim"
ec['vigencia_fim'] = ec['vigencia_fim'].replace('Indeterminado', '31/12/2026')

#trocar tipo de coluna "vigencia_inicio" e "vigencia_fim" para datetime
ec['vigencia_inicio'] = pd.to_datetime(ec['vigencia_inicio'], format='%d/%m/%Y')
ec['vigencia_fim'] = pd.to_datetime(ec['vigencia_fim'], format='%d/%m/%Y')

# trocar "Indetermindado" por valor 0 na coluna "numero_parcelas"
ec['numero_parcelas'] = ec['numero_parcelas'].replace('Indeterminado', 0)

display(ec.head())
ec.info()

,numero_instrumento,vigencia_inicio,vigencia_fim,valor_global,numero_parcelas,valor_parcela
0,00002/2022,2022-03-01,2027-03-01,"R$ 32.782,62",12,"R$ 2.731,89"
1,00002/2023,2023-02-21,2027-02-21,"R$ 91.030,42",12,"R$ 7.585,87"
2,00017/2025,2025-11-10,2026-12-31,"R$ 19.224,64",0,"R$ 19.224,64"
3,00009/2025,2025-06-16,2026-12-31,"R$ 563.133,96",0,"R$ 563.133,96"
4,00033/2024,2024-09-04,2026-09-04,"R$ 301.377,60",12,"R$ 25.114,80"

<class 'pandas.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   numero_instrumento  147 non-null    str
 1   vigencia_inicio     147 non-null    datetime64[us]
 2   vigencia_fim        147 non-null    datetime64[us]
 3   valor_global        147 non-null    str
 4   numero_parcelas     147 non-null    object
 5   valor_parcela       147 non-null    str
dtypes: datetime64[us](2), object(1), str(3)
memory usage: 7.0+ KB

In [184]:
# mudar colunas R$_Valor_Global e R$_Valor_Parcela para float
ec['valor_global'] = (
    ec['valor_global']
    .astype(str)
    .str.replace(r'[R$\s.]', '', regex=True)  # remove R$, espaços e pontos
    .str.replace(',', '.', regex=False)       # troca vírgula por ponto
)
ec['valor_global'] = pd.to_numeric(ec['valor_global'], errors='coerce')
ec['valor_global'] = ec['valor_global'].fillna(0)

ec['valor_parcela'] = (
    ec['valor_parcela']
    .astype(str)
    .str.replace(r'[R$\s.]', '', regex=True)  # remove R$, espaços e pontos
    .str.replace(',', '.', regex=False)       # troca vírgula por ponto
)
ec['valor_parcela'] = pd.to_numeric(ec['valor_parcela'], errors='coerce')
ec['valor_parcela'] = ec['valor_parcela'].fillna(0)

display(ec.head())
ec.info()

,numero_instrumento,vigencia_inicio,vigencia_fim,valor_global,numero_parcelas,valor_parcela
0,00002/2022,2022-03-01,2027-03-01,32782.62,12,2731.89
1,00002/2023,2023-02-21,2027-02-21,91030.42,12,7585.87
2,00017/2025,2025-11-10,2026-12-31,19224.64,0,19224.64
3,00009/2025,2025-06-16,2026-12-31,563133.96,0,563133.96
4,00033/2024,2024-09-04,2026-09-04,301377.60,12,25114.80

<class 'pandas.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   numero_instrumento  147 non-null    str
 1   vigencia_inicio     147 non-null    datetime64[us]
 2   vigencia_fim        147 non-null    datetime64[us]
 3   valor_global        147 non-null    float64
 4   numero_parcelas     147 non-null    object
 5   valor_parcela       147 non-null    float64
dtypes: datetime64[us](2), float64(2), object(1), str(1)
memory usage: 7.0+ KB

In [185]:
# calcular a diferença entre as datas "vigencia_fim" e "vigencia_inicio" e criar uma nova coluna "duracao_contrato" tipo Int representando a duração do contrato em meses
ec['duracao_contrato'] = (ec['vigencia_fim'] - ec['vigencia_inicio']).dt.days / 30
ec['duracao_contrato'] = ec['duracao_contrato'].astype(int)
display(ec.head())

,numero_instrumento,vigencia_inicio,vigencia_fim,valor_global,numero_parcelas,valor_parcela,duracao_contrato
0,00002/2022,2022-03-01,2027-03-01,32782.62,12,2731.89,60
1,00002/2023,2023-02-21,2027-02-21,91030.42,12,7585.87,48
2,00017/2025,2025-11-10,2026-12-31,19224.64,0,19224.64,13
3,00009/2025,2025-06-16,2026-12-31,563133.96,0,563133.96,18
4,00033/2024,2024-09-04,2026-09-04,301377.60,12,25114.80,24

In [186]:
# fazer comparação entre a coluna "duracao_contrato" e "numero_parcelas" e criar uma lista mnostrando todos os registros que são diferentes
diferentes_parcelas = ec[ec['duracao_contrato'] != ec['numero_parcelas']]
display(diferentes_parcelas)
ec.info()

,numero_instrumento,vigencia_inicio,vigencia_fim,valor_global,numero_parcelas,valor_parcela,duracao_contrato
0,00002/2022,2022-03-01,2027-03-01,32782.62,12,2731.89,60
1,00002/2023,2023-02-21,2027-02-21,91030.42,12,7585.87,48
2,00017/2025,2025-11-10,2026-12-31,19224.64,0,19224.64,13
3,00009/2025,2025-06-16,2026-12-31,563133.96,0,563133.96,18
4,00033/2024,2024-09-04,2026-09-04,301377.60,12,25114.80,24
...,...,...,...,...,...,...,...
139,00068/2024,2014-02-14,2026-12-31,9372.00,0,9372.00,156
140,00062/2024,2014-02-06,2026-12-31,231000.00,0,231000.00,157
141,00061/2024,2014-02-06,2026-12-31,310200.00,0,310200.00,157
142,2025NE000067,2025-01-30,2025-12-31,1300.00,1,1300.00,11
143,2025NE000012,2025-01-20,2025-12-31,880.00,1,880.00,11

<class 'pandas.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   numero_instrumento  147 non-null    str
 1   vigencia_inicio     147 non-null    datetime64[us]
 2   vigencia_fim        147 non-null    datetime64[us]
 3   valor_global        147 non-null    float64
 4   numero_parcelas     147 non-null    object
 5   valor_parcela       147 non-null    float64
 6   duracao_contrato    147 non-null    int64
dtypes: datetime64[us](2), float64(2), int64(1), object(1), str(1)
memory usage: 8.2+ KB

In [187]:
# coluna valor_global dividir pela coluna duração do contrato e criar uma nova coluna "valor_parcela_calculado"
ec['valor_parcela_calculado'] = ec['valor_global'] / ec['duracao_contrato']

# fazer tratamento na coluna "valor_parcela_calculado" para arredondar para 2 casas decimais
ec['valor_parcela_calculado'] = ec['valor_parcela_calculado'].round(2)

# mostrar todos os registros da planilha
display(ec.head())
ec.info()

,numero_instrumento,vigencia_inicio,vigencia_fim,valor_global,numero_parcelas,valor_parcela,duracao_contrato,valor_parcela_calculado
0,00002/2022,2022-03-01,2027-03-01,32782.62,12,2731.89,60,546.38
1,00002/2023,2023-02-21,2027-02-21,91030.42,12,7585.87,48,1896.47
2,00017/2025,2025-11-10,2026-12-31,19224.64,0,19224.64,13,1478.82
3,00009/2025,2025-06-16,2026-12-31,563133.96,0,563133.96,18,31285.22
4,00033/2024,2024-09-04,2026-09-04,301377.60,12,25114.80,24,12557.40

<class 'pandas.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   numero_instrumento       147 non-null    str
 1   vigencia_inicio          147 non-null    datetime64[us]
 2   vigencia_fim             147 non-null    datetime64[us]
 3   valor_global             147 non-null    float64
 4   numero_parcelas          147 non-null    object
 5   valor_parcela            147 non-null    float64
 6   duracao_contrato         147 non-null    int64
 7   valor_parcela_calculado  147 non-null    float64
dtypes: datetime64[us](2), float64(3), int64(1), object(1), str(1)
memory usage: 9.3+ KB

In [188]:
# listar os registros onde a coluna "valor_parcela_calculado" é diferente da coluna "valor_parcela"
diferentes_valor_parcela = ec[ec['valor_parcela_calculado'] != ec['valor_parcela']]
display(diferentes_valor_parcela)

#listar os registros onde a coluna "valor_parcela_calculado" é igual a coluna "valor_parcela"
iguais_valor_parcela = ec[ec['valor_parcela_calculado'] == ec['valor_parcela']]
display(iguais_valor_parcela)

,numero_instrumento,vigencia_inicio,vigencia_fim,valor_global,numero_parcelas,valor_parcela,duracao_contrato,valor_parcela_calculado
0,00002/2022,2022-03-01,2027-03-01,32782.62,12,2731.89,60,546.38
1,00002/2023,2023-02-21,2027-02-21,91030.42,12,7585.87,48,1896.47
2,00017/2025,2025-11-10,2026-12-31,19224.64,0,19224.64,13,1478.82
3,00009/2025,2025-06-16,2026-12-31,563133.96,0,563133.96,18,31285.22
4,00033/2024,2024-09-04,2026-09-04,301377.60,12,25114.80,24,12557.40
...,...,...,...,...,...,...,...,...
139,00068/2024,2014-02-14,2026-12-31,9372.00,0,9372.00,156,60.08
140,00062/2024,2014-02-06,2026-12-31,231000.00,0,231000.00,157,1471.34
141,00061/2024,2014-02-06,2026-12-31,310200.00,0,310200.00,157,1975.80
142,2025NE000067,2025-01-30,2025-12-31,1300.00,1,1300.00,11,118.18
143,2025NE000012,2025-01-20,2025-12-31,880.00,1,880.00,11,80.00

,numero_instrumento,vigencia_inicio,vigencia_fim,valor_global,numero_parcelas,valor_parcela,duracao_contrato,valor_parcela_calculado
7,00002/2026,2026-01-06,2027-01-05,1980.00,12,165.00,12,165.00
8,00003/2026,2026-01-16,2027-01-16,7092.92,12,591.08,12,591.08
9,00010/2025,2025-05-27,2030-05-27,10728300.00,60,178805.00,60,178805.00
31,00012/2025,2025-05-15,2030-05-15,2881185.60,60,48019.76,60,48019.76
32,00033/2025,2025-10-29,2026-10-29,519222.00,12,43268.50,12,43268.50
37,00005/2026,2026-02-18,2027-02-18,516328.32,12,43027.36,12,43027.36
38,00013/2025,2025-06-12,2030-06-12,1465684.20,60,24428.07,60,24428.07
49,00004/2026,2026-01-16,2027-01-16,460729.92,12,38394.16,12,38394.16
62,00038/2024,2024-09-30,2029-09-30,8644770.00,60,144079.50,60,144079.50
64,2025NE000380,2025-11-06,2025-12-31,1510.00,1,1510.00,1,1510.00
87,00029/2025,2025-10-13,2026-10-13,632600.00,12,52716.67,12,52716.67
89,00023/2025,2025-10-06,2026-10-06,524462.76,12,43705.23,12,43705.23
93,00007/2025,2025-03-26,2030-03-26,268309.72,60,4471.83,60,4471.83
96,00018/2025,2025-07-21,2030-07-21,89799.60,60,1496.66,60,1496.66
101,00006/2024,2024-02-16,2029-02-16,102873.60,60,1714.56,60,1714.56
104,00002/2024,2024-01-18,2029-01-18,32601900.00,60,543365.00,60,543365.00
115,00016/2025,2025-08-08,2026-08-08,191776.20,12,15981.35,12,15981.35
116,00015/2025,2025-08-04,2026-08-04,80326.57,12,6693.88,12,6693.88
131,00001/2025,2025-01-27,2030-01-27,86499.45,60,1441.66,60,1441.66
135,00045/2024,2024-12-12,2029-12-12,44625.60,60,743.76,60,743.76
136,00016/2023,2023-07-24,2028-07-24,75087.60,60,1251.46,60,1251.46
137,00024/2023,2023-11-10,2026-11-09,111915.33,36,3108.76,36,3108.76
144,00034/2025,2026-01-04,2027-01-04,438568.44,12,36547.37,12,36547.37
145,00009/2022,2023-06-15,2024-06-14,20000.00,12,1666.67,12,1666.67
146,09001/2016,2021-10-01,2026-09-30,0.00,60,0.00,60,0.00

In [189]:
# exportar em abas diferente mas na mesma planilha
with pd.ExcelWriter('erros_contratos_comparacao.xlsx') as writer:
    ec.to_excel(writer, sheet_name='Contratos_Reprogramado', index=False)
    diferentes_valor_parcela.to_excel(writer, sheet_name='Diferentes_Valor_Parcela', index=False)
    iguais_valor_parcela.to_excel(writer, sheet_name='Iguais_Valor_Parcela', index=False)