In [1]:
# Importação das Bibliotecas
import pandas as pd # para manipulação de dados

In [2]:
# Carregamento da base de Dados - Contratos
base_contratos = pd.read_excel('contratos_comprasnet.xlsx', header=1)

# excluindo todos os espaços desnecessários do início e do fim dos valores das colunas
base_contratos = base_contratos.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

display(base_contratos.head(5))
base_contratos.info()

,Número do instrumento,Unidades Requisitantes,Categoria,Subcategoria,Fornecedor,Processo,Objeto,Vig. Início,Vig. Fim,Valor Global,Núm. Parcelas,Valor Parcela,Prorrogável,Antecipa Gov,Atualizado em,Data Encerramento,ID do Contrato
0,00030/2022,CE (PSF-Sobral e PSF-Juazeiro do Norte),Serviços de Engenharia,MANUTENÇÃO PREDIAL,34.016.448/0001-15 - PROJETCONS ENGENHARIA E A...,00587.001443/2022-98,O OBJETO DO PRESENTE INSTRUMENTO É A CONTRATAÇ...,05/09/2022,05/09/2026,"R$ 112.687,44",12,"R$ 9.390,62",Sim,Não,23/07/2026 15:24,NaN,158697
1,00012/2015,CE (PSF-SOB),Locação Imóveis,LOCAÇÃO TRADICIONAL,045.804.863-15 - CIRO BELCHIOR ROCHA,00663.000104/2014-24,LOCAÇÇAO DE IMÓVEL LOCALIZADO NA RUA VICENTE R...,06/02/2015,06/02/2030,"R$ 624.985,20",60,"R$ 10.416,42",Sim,Não,23/07/2026 08:42,NaN,3059
2,00006/2026,"CE (PU, PF, CJU e NOVA SEDE)",Serviços de Engenharia,MANUTENÇÃO PREDIAL,01.335.973/0001-44 - JUDAH SERVICOS DE ENGENHA...,00587.001573/2024-92,CONTRATAÇÃO DE EMPRESA PARA PRESTAÇÃO DE SERVI...,21/02/2026,26/02/2027,"R$ 323.266,56",12,"R$ 26.938,88",Sim,Não,21/07/2026 11:15,NaN,810877
3,00013/2022,"CE (PU, PF, CJU e EAGU)",Serviços,MANUTENÇÃO DE AR CONDICIONADO,07.531.234/0001-04 - IMQPA - INSTITUTO MINEIRO...,00587.000977/2021-16,CONTRATAÇÃO DE SERVIÇOS DE MANUTENÇÃO PREVENTI...,02/06/2022,02/06/2027,"R$ 305.936,36",12,"R$ 25.494,70",Sim,Não,21/07/2026 10:59,NaN,145967
4,00025/2015,"CE (PU, PF, CJU e UEA)",Locação Imóveis,LOCAÇÃO TRADICIONAL,18.114.711/0001-52 - R D EMPREEDIMENTOS IMOBIL...,00587.000866/2015-61,LOCAÇÃO DE SALAS COMERCIAIS LOCALIZADAS NO 5º ...,23/11/2015,15/03/2028,"R$ 2.256.541,20",60,"R$ 37.609,02",Sim,Não,21/07/2026 10:52,NaN,2973

<class 'pandas.DataFrame'>
RangeIndex: 162 entries, 0 to 161
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Número do instrumento   162 non-null    str
 1   Unidades Requisitantes  144 non-null    str
 2   Categoria               162 non-null    str
 3   Subcategoria            134 non-null    str
 4   Fornecedor              162 non-null    str
 5   Processo                162 non-null    str
 6   Objeto                  162 non-null    str
 7   Vig. Início             162 non-null    str
 8   Vig. Fim                162 non-null    str
 9   Valor Global            162 non-null    str
 10  Núm. Parcelas           162 non-null    int64
 11  Valor Parcela           162 non-null    str
 12  Prorrogável             162 non-null    str
 13  Antecipa Gov            162 non-null    str
 14  Atualizado em           162 non-null    str
 15  Data Encerramento       0 non-null      float64
 16  ID do Contrato          162 non-null    int64
dtypes: float64(1), int64(2), str(14)
memory usage: 21.6 KB

In [3]:
# Exclusão de colunas desnecessárias
colunas_excluir = ['Atualizado em', 'Antecipa Gov', 'Data Encerramento', 'Núm. Parcelas', 'Valor Global']
base_contratos = base_contratos.drop(columns=colunas_excluir)

# removendo colunas vazias
#base_contratos.dropna(axis=1, how='all', inplace=True)

# removendo linhas inválidas
#base_contratos = base_contratos[base_contratos['Unidades Requisitantes'].notna()]
base_contratos = base_contratos[base_contratos['Unidades Requisitantes'] != "'-8"]
# substituir celulas vazias por 'Não informado' na coluna 'Unidades Requisitantes'
base_contratos['Unidades Requisitantes'].fillna('Não informado', inplace=True)
base_contratos = base_contratos[base_contratos['Número do instrumento'].notna()]
base_contratos = base_contratos[base_contratos['Número do instrumento'] != "'-8"]

# onde tiver valores nulos em todas as colunas, substituir por 'Não informado'
base_contratos.fillna('Não informado', inplace=True) 


display(base_contratos.head(5))
base_contratos.info()

C:\Users\luis.henrique\AppData\Local\Temp\ipykernel_7648\2596046191.py:12: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  base_contratos['Unidades Requisitantes'].fillna('Não informado', inplace=True)

,Número do instrumento,Unidades Requisitantes,Categoria,Subcategoria,Fornecedor,Processo,Objeto,Vig. Início,Vig. Fim,Valor Parcela,Prorrogável,ID do Contrato
0,00030/2022,CE (PSF-Sobral e PSF-Juazeiro do Norte),Serviços de Engenharia,MANUTENÇÃO PREDIAL,34.016.448/0001-15 - PROJETCONS ENGENHARIA E A...,00587.001443/2022-98,O OBJETO DO PRESENTE INSTRUMENTO É A CONTRATAÇ...,05/09/2022,05/09/2026,"R$ 9.390,62",Sim,158697
1,00012/2015,CE (PSF-SOB),Locação Imóveis,LOCAÇÃO TRADICIONAL,045.804.863-15 - CIRO BELCHIOR ROCHA,00663.000104/2014-24,LOCAÇÇAO DE IMÓVEL LOCALIZADO NA RUA VICENTE R...,06/02/2015,06/02/2030,"R$ 10.416,42",Sim,3059
2,00006/2026,"CE (PU, PF, CJU e NOVA SEDE)",Serviços de Engenharia,MANUTENÇÃO PREDIAL,01.335.973/0001-44 - JUDAH SERVICOS DE ENGENHA...,00587.001573/2024-92,CONTRATAÇÃO DE EMPRESA PARA PRESTAÇÃO DE SERVI...,21/02/2026,26/02/2027,"R$ 26.938,88",Sim,810877
3,00013/2022,"CE (PU, PF, CJU e EAGU)",Serviços,MANUTENÇÃO DE AR CONDICIONADO,07.531.234/0001-04 - IMQPA - INSTITUTO MINEIRO...,00587.000977/2021-16,CONTRATAÇÃO DE SERVIÇOS DE MANUTENÇÃO PREVENTI...,02/06/2022,02/06/2027,"R$ 25.494,70",Sim,145967
4,00025/2015,"CE (PU, PF, CJU e UEA)",Locação Imóveis,LOCAÇÃO TRADICIONAL,18.114.711/0001-52 - R D EMPREEDIMENTOS IMOBIL...,00587.000866/2015-61,LOCAÇÃO DE SALAS COMERCIAIS LOCALIZADAS NO 5º ...,23/11/2015,15/03/2028,"R$ 37.609,02",Sim,2973

<class 'pandas.DataFrame'>
RangeIndex: 162 entries, 0 to 161
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Número do instrumento   162 non-null    str
 1   Unidades Requisitantes  162 non-null    str
 2   Categoria               162 non-null    str
 3   Subcategoria            162 non-null    str
 4   Fornecedor              162 non-null    str
 5   Processo                162 non-null    str
 6   Objeto                  162 non-null    str
 7   Vig. Início             162 non-null    str
 8   Vig. Fim                162 non-null    str
 9   Valor Parcela           162 non-null    str
 10  Prorrogável             162 non-null    str
 11  ID do Contrato          162 non-null    int64
dtypes: int64(1), str(11)
memory usage: 15.3 KB

In [4]:
# mudar nome das colunas para facilitar a manipulação
base_contratos = base_contratos.rename(columns=
                                       {'Número do instrumento': 'contratos_num_instrumento',
                                        'Unidades Requisitantes': 'contratos_unid_requisitantes',
                                        'Categoria': 'contratos_categoria',
                                        'Subcategoria': 'contratos_sub_categoria',
                                        'Fornecedor': 'contratos_doc_fornecedor',
                                        'Processo': 'contratos_NUP',
                                        'Objeto': 'contratos_objeto',
                                        'Vig. Início': 'contratos_vigencia_inicio',
                                        'Vig. Fim': 'contratos_vigencia_fim',
                                        'Valor Parcela': 'contratos_valor_parcela',
                                        'Prorrogável': 'contratos_prorrogavel'
                                       })


base_contratos['contratos_unid_requisitantes'] = base_contratos['contratos_unid_requisitantes'].replace('null', 'Em Branco')

# Converter colunas de data para date
base_contratos['contratos_vigencia_inicio'] = pd.to_datetime(base_contratos['contratos_vigencia_inicio'], dayfirst=True, errors='coerce')
base_contratos['contratos_vigencia_fim'] = base_contratos['contratos_vigencia_fim'].replace('Indeterminado', '31/12/2026')
base_contratos['contratos_vigencia_fim'] = pd.to_datetime(base_contratos['contratos_vigencia_fim'], dayfirst=True, errors='coerce')

# retirar os pontos e virgulas da coluna cnpj e cpf deixar apenas os números
# base_contratos['contratos_doc_fornecedor'] = base_contratos['contratos_doc_fornecedor'].str.replace('.', '', regex=False).str.replace('-', '', regex=False).str.replace('/', '', regex=False)


display(base_contratos.head(5))
base_contratos.info()

,contratos_num_instrumento,contratos_unid_requisitantes,contratos_categoria,contratos_sub_categoria,contratos_doc_fornecedor,contratos_NUP,contratos_objeto,contratos_vigencia_inicio,contratos_vigencia_fim,contratos_valor_parcela,contratos_prorrogavel,ID do Contrato
0,00030/2022,CE (PSF-Sobral e PSF-Juazeiro do Norte),Serviços de Engenharia,MANUTENÇÃO PREDIAL,34.016.448/0001-15 - PROJETCONS ENGENHARIA E A...,00587.001443/2022-98,O OBJETO DO PRESENTE INSTRUMENTO É A CONTRATAÇ...,2022-09-05,2026-09-05,"R$ 9.390,62",Sim,158697
1,00012/2015,CE (PSF-SOB),Locação Imóveis,LOCAÇÃO TRADICIONAL,045.804.863-15 - CIRO BELCHIOR ROCHA,00663.000104/2014-24,LOCAÇÇAO DE IMÓVEL LOCALIZADO NA RUA VICENTE R...,2015-02-06,2030-02-06,"R$ 10.416,42",Sim,3059
2,00006/2026,"CE (PU, PF, CJU e NOVA SEDE)",Serviços de Engenharia,MANUTENÇÃO PREDIAL,01.335.973/0001-44 - JUDAH SERVICOS DE ENGENHA...,00587.001573/2024-92,CONTRATAÇÃO DE EMPRESA PARA PRESTAÇÃO DE SERVI...,2026-02-21,2027-02-26,"R$ 26.938,88",Sim,810877
3,00013/2022,"CE (PU, PF, CJU e EAGU)",Serviços,MANUTENÇÃO DE AR CONDICIONADO,07.531.234/0001-04 - IMQPA - INSTITUTO MINEIRO...,00587.000977/2021-16,CONTRATAÇÃO DE SERVIÇOS DE MANUTENÇÃO PREVENTI...,2022-06-02,2027-06-02,"R$ 25.494,70",Sim,145967
4,00025/2015,"CE (PU, PF, CJU e UEA)",Locação Imóveis,LOCAÇÃO TRADICIONAL,18.114.711/0001-52 - R D EMPREEDIMENTOS IMOBIL...,00587.000866/2015-61,LOCAÇÃO DE SALAS COMERCIAIS LOCALIZADAS NO 5º ...,2015-11-23,2028-03-15,"R$ 37.609,02",Sim,2973

<class 'pandas.DataFrame'>
RangeIndex: 162 entries, 0 to 161
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   contratos_num_instrumento     162 non-null    str
 1   contratos_unid_requisitantes  162 non-null    str
 2   contratos_categoria           162 non-null    str
 3   contratos_sub_categoria       162 non-null    str
 4   contratos_doc_fornecedor      162 non-null    str
 5   contratos_NUP                 162 non-null    str
 6   contratos_objeto              162 non-null    str
 7   contratos_vigencia_inicio     162 non-null    datetime64[us]
 8   contratos_vigencia_fim        162 non-null    datetime64[us]
 9   contratos_valor_parcela       162 non-null    str
 10  contratos_prorrogavel         162 non-null    str
 11  ID do Contrato                162 non-null    int64
dtypes: datetime64[us](2), int64(1), str(9)
memory usage: 15.3 KB

In [5]:
# criar uma coluna com o nome "vigencia_contrato" de acordo com o calculo das colunas vigencia_inicio e vigencia_fim, tipo de dados inteiro.
#base_contratos['vigencia_contrato'] = ((base_contratos['vigencia_fim'] - base_contratos['vigencia_inicio']) / np.timedelta64(1, 'M')).astype(int)

base_contratos['contratos_vigencia_contrato'] = (
    (base_contratos['contratos_vigencia_fim'].dt.year - base_contratos['contratos_vigencia_inicio'].dt.year) * 12 +
    (base_contratos['contratos_vigencia_fim'].dt.month - base_contratos['contratos_vigencia_inicio'].dt.month)
)

# converter a coluna valor_parcela para float, retirando os pontos e virgulas e convertendo para o formato americano (ponto como separador decimal)
base_contratos['contratos_valor_parcela'] = pd.to_numeric(
    base_contratos['contratos_valor_parcela']
    .astype(str)
    .str.replace('R$', '', regex=False)
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
    .str.strip(),
    errors='coerce'
)

# multipicar a coluna valor_parcela pela coluna vigencia_contrato e criar uma nova coluna chamada valor_total_contrato
base_contratos['contratos_valor_global'] = base_contratos['contratos_valor_parcela'] * base_contratos['contratos_vigencia_contrato']


display(base_contratos.head(5))
base_contratos.info()

,contratos_num_instrumento,contratos_unid_requisitantes,contratos_categoria,contratos_sub_categoria,contratos_doc_fornecedor,contratos_NUP,contratos_objeto,contratos_vigencia_inicio,contratos_vigencia_fim,contratos_valor_parcela,contratos_prorrogavel,ID do Contrato,contratos_vigencia_contrato,contratos_valor_global
0,00030/2022,CE (PSF-Sobral e PSF-Juazeiro do Norte),Serviços de Engenharia,MANUTENÇÃO PREDIAL,34.016.448/0001-15 - PROJETCONS ENGENHARIA E A...,00587.001443/2022-98,O OBJETO DO PRESENTE INSTRUMENTO É A CONTRATAÇ...,2022-09-05,2026-09-05,9390.62,Sim,158697,48,450749.76
1,00012/2015,CE (PSF-SOB),Locação Imóveis,LOCAÇÃO TRADICIONAL,045.804.863-15 - CIRO BELCHIOR ROCHA,00663.000104/2014-24,LOCAÇÇAO DE IMÓVEL LOCALIZADO NA RUA VICENTE R...,2015-02-06,2030-02-06,10416.42,Sim,3059,180,1874955.60
2,00006/2026,"CE (PU, PF, CJU e NOVA SEDE)",Serviços de Engenharia,MANUTENÇÃO PREDIAL,01.335.973/0001-44 - JUDAH SERVICOS DE ENGENHA...,00587.001573/2024-92,CONTRATAÇÃO DE EMPRESA PARA PRESTAÇÃO DE SERVI...,2026-02-21,2027-02-26,26938.88,Sim,810877,12,323266.56
3,00013/2022,"CE (PU, PF, CJU e EAGU)",Serviços,MANUTENÇÃO DE AR CONDICIONADO,07.531.234/0001-04 - IMQPA - INSTITUTO MINEIRO...,00587.000977/2021-16,CONTRATAÇÃO DE SERVIÇOS DE MANUTENÇÃO PREVENTI...,2022-06-02,2027-06-02,25494.70,Sim,145967,60,1529682.00
4,00025/2015,"CE (PU, PF, CJU e UEA)",Locação Imóveis,LOCAÇÃO TRADICIONAL,18.114.711/0001-52 - R D EMPREEDIMENTOS IMOBIL...,00587.000866/2015-61,LOCAÇÃO DE SALAS COMERCIAIS LOCALIZADAS NO 5º ...,2015-11-23,2028-03-15,37609.02,Sim,2973,148,5566134.96

<class 'pandas.DataFrame'>
RangeIndex: 162 entries, 0 to 161
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   contratos_num_instrumento     162 non-null    str
 1   contratos_unid_requisitantes  162 non-null    str
 2   contratos_categoria           162 non-null    str
 3   contratos_sub_categoria       162 non-null    str
 4   contratos_doc_fornecedor      162 non-null    str
 5   contratos_NUP                 162 non-null    str
 6   contratos_objeto              162 non-null    str
 7   contratos_vigencia_inicio     162 non-null    datetime64[us]
 8   contratos_vigencia_fim        162 non-null    datetime64[us]
 9   contratos_valor_parcela       162 non-null    float64
 10  contratos_prorrogavel         162 non-null    str
 11  ID do Contrato                162 non-null    int64
 12  contratos_vigencia_contrato   162 non-null    int32
 13  contratos_valor_global        162 non-null    float64
dtypes: datetime64[us](2), float64(2), int32(1), int64(1), str(8)
memory usage: 17.2 KB

In [6]:
# utilizar apenas os registros da coluna "numero_instrumento" que terminem com 2025 e 2026
#base_contratos = base_contratos[base_contratos['contratos_num_instrumento'].str.endswith(('2023','2024','2025', '2026'))]

display(base_contratos.head(5))
base_contratos.info()

,contratos_num_instrumento,contratos_unid_requisitantes,contratos_categoria,contratos_sub_categoria,contratos_doc_fornecedor,contratos_NUP,contratos_objeto,contratos_vigencia_inicio,contratos_vigencia_fim,contratos_valor_parcela,contratos_prorrogavel,ID do Contrato,contratos_vigencia_contrato,contratos_valor_global
0,00030/2022,CE (PSF-Sobral e PSF-Juazeiro do Norte),Serviços de Engenharia,MANUTENÇÃO PREDIAL,34.016.448/0001-15 - PROJETCONS ENGENHARIA E A...,00587.001443/2022-98,O OBJETO DO PRESENTE INSTRUMENTO É A CONTRATAÇ...,2022-09-05,2026-09-05,9390.62,Sim,158697,48,450749.76
1,00012/2015,CE (PSF-SOB),Locação Imóveis,LOCAÇÃO TRADICIONAL,045.804.863-15 - CIRO BELCHIOR ROCHA,00663.000104/2014-24,LOCAÇÇAO DE IMÓVEL LOCALIZADO NA RUA VICENTE R...,2015-02-06,2030-02-06,10416.42,Sim,3059,180,1874955.60
2,00006/2026,"CE (PU, PF, CJU e NOVA SEDE)",Serviços de Engenharia,MANUTENÇÃO PREDIAL,01.335.973/0001-44 - JUDAH SERVICOS DE ENGENHA...,00587.001573/2024-92,CONTRATAÇÃO DE EMPRESA PARA PRESTAÇÃO DE SERVI...,2026-02-21,2027-02-26,26938.88,Sim,810877,12,323266.56
3,00013/2022,"CE (PU, PF, CJU e EAGU)",Serviços,MANUTENÇÃO DE AR CONDICIONADO,07.531.234/0001-04 - IMQPA - INSTITUTO MINEIRO...,00587.000977/2021-16,CONTRATAÇÃO DE SERVIÇOS DE MANUTENÇÃO PREVENTI...,2022-06-02,2027-06-02,25494.70,Sim,145967,60,1529682.00
4,00025/2015,"CE (PU, PF, CJU e UEA)",Locação Imóveis,LOCAÇÃO TRADICIONAL,18.114.711/0001-52 - R D EMPREEDIMENTOS IMOBIL...,00587.000866/2015-61,LOCAÇÃO DE SALAS COMERCIAIS LOCALIZADAS NO 5º ...,2015-11-23,2028-03-15,37609.02,Sim,2973,148,5566134.96

<class 'pandas.DataFrame'>
RangeIndex: 162 entries, 0 to 161
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   contratos_num_instrumento     162 non-null    str
 1   contratos_unid_requisitantes  162 non-null    str
 2   contratos_categoria           162 non-null    str
 3   contratos_sub_categoria       162 non-null    str
 4   contratos_doc_fornecedor      162 non-null    str
 5   contratos_NUP                 162 non-null    str
 6   contratos_objeto              162 non-null    str
 7   contratos_vigencia_inicio     162 non-null    datetime64[us]
 8   contratos_vigencia_fim        162 non-null    datetime64[us]
 9   contratos_valor_parcela       162 non-null    float64
 10  contratos_prorrogavel         162 non-null    str
 11  ID do Contrato                162 non-null    int64
 12  contratos_vigencia_contrato   162 non-null    int32
 13  contratos_valor_global        162 non-null    float64
dtypes: datetime64[us](2), float64(2), int32(1), int64(1), str(8)
memory usage: 17.2 KB

In [7]:
# excluir os registros que tenham a coluna 'contratos_vigencia_fim' menor do que a data atual.

#base_contratos['contratos_vigencia_fim'] = pd.to_datetime(base_contratos['contratos_vigencia_fim'])

#hoje = pd.Timestamp.today().normalize()

#indices_excluir = base_contratos[base_contratos['contratos_vigencia_fim'] < hoje].index
#base_contratos = base_contratos.drop(indices_excluir)

display(base_contratos)
base_contratos.info()

,contratos_num_instrumento,contratos_unid_requisitantes,contratos_categoria,contratos_sub_categoria,contratos_doc_fornecedor,contratos_NUP,contratos_objeto,contratos_vigencia_inicio,contratos_vigencia_fim,contratos_valor_parcela,contratos_prorrogavel,ID do Contrato,contratos_vigencia_contrato,contratos_valor_global
0,00030/2022,CE (PSF-Sobral e PSF-Juazeiro do Norte),Serviços de Engenharia,MANUTENÇÃO PREDIAL,34.016.448/0001-15 - PROJETCONS ENGENHARIA E A...,00587.001443/2022-98,O OBJETO DO PRESENTE INSTRUMENTO É A CONTRATAÇ...,2022-09-05,2026-09-05,9390.62,Sim,158697,48,450749.76
1,00012/2015,CE (PSF-SOB),Locação Imóveis,LOCAÇÃO TRADICIONAL,045.804.863-15 - CIRO BELCHIOR ROCHA,00663.000104/2014-24,LOCAÇÇAO DE IMÓVEL LOCALIZADO NA RUA VICENTE R...,2015-02-06,2030-02-06,10416.42,Sim,3059,180,1874955.60
2,00006/2026,"CE (PU, PF, CJU e NOVA SEDE)",Serviços de Engenharia,MANUTENÇÃO PREDIAL,01.335.973/0001-44 - JUDAH SERVICOS DE ENGENHA...,00587.001573/2024-92,CONTRATAÇÃO DE EMPRESA PARA PRESTAÇÃO DE SERVI...,2026-02-21,2027-02-26,26938.88,Sim,810877,12,323266.56
3,00013/2022,"CE (PU, PF, CJU e EAGU)",Serviços,MANUTENÇÃO DE AR CONDICIONADO,07.531.234/0001-04 - IMQPA - INSTITUTO MINEIRO...,00587.000977/2021-16,CONTRATAÇÃO DE SERVIÇOS DE MANUTENÇÃO PREVENTI...,2022-06-02,2027-06-02,25494.70,Sim,145967,60,1529682.00
4,00025/2015,"CE (PU, PF, CJU e UEA)",Locação Imóveis,LOCAÇÃO TRADICIONAL,18.114.711/0001-52 - R D EMPREEDIMENTOS IMOBIL...,00587.000866/2015-61,LOCAÇÃO DE SALAS COMERCIAIS LOCALIZADAS NO 5º ...,2015-11-23,2028-03-15,37609.02,Sim,2973,148,5566134.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,2024NE000359,PE/RE/CJU;PE/RE/ESAGU;PE/RE/PRF;PE/RE/PRU;PE/R...,Serviços,PERSIANAS,89.278.519/0001-40 - MARCENARIA SULAR LTDA,00587.001699/2024-67,CONTRATAÇÃO DO SERVIÇO DE FABRICAÇÃO E MONTAGE...,2024-09-25,2024-12-31,350352.00,Sim,530618,3,1051056.00
158,2025NE000068,BA/FS/PSF,Serviços,Não informado,14.588.818/0001-81 - COPIADORA UNIVERSITARIA LTDA,00492.006572/2018-45,ATENDER DESPESA COM O PAGAMENTO DA TAXA DE CON...,2025-01-30,2025-12-31,7508.74,Não,439460,11,82596.14
159,2025NE000067,AL/MA/CJU,Serviços,Não informado,13.938.116/0001-18 - ANCAR - ADMINISTRADORES D...,00587.002511/2010-01,ATENDER DESPESA COM O PAGAMENTO DA TAXA DE CO...,2025-01-30,2025-12-31,1300.00,Não,439458,11,14300.00
160,2025NE000012,CE/SO/PSF,Serviços,Não informado,34.155.401/0001-32 - EVOLUTION NEGOCIOS EMPRES...,00587.002511/2010-01,PRESTAÇÃO DE SERVIÇOS TECNICOS PROFISSIONAIS D...,2025-01-20,2025-12-31,880.00,Não,431397,11,9680.00
161,00009/2022,Unidades São Luís/MA,Serviços,ÁGUA E ESGOTO,06.274.757/0001-50 - COMPANHIA DE SANEAMENTO A...,00464.002850/2015-80,SERVIÇOS DE ABASTECIMENTO DE ÁGUA E COLETA DE ...,2023-06-15,2024-06-14,1666.67,Sim,157406,12,20000.04

<class 'pandas.DataFrame'>
RangeIndex: 162 entries, 0 to 161
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   contratos_num_instrumento     162 non-null    str
 1   contratos_unid_requisitantes  162 non-null    str
 2   contratos_categoria           162 non-null    str
 3   contratos_sub_categoria       162 non-null    str
 4   contratos_doc_fornecedor      162 non-null    str
 5   contratos_NUP                 162 non-null    str
 6   contratos_objeto              162 non-null    str
 7   contratos_vigencia_inicio     162 non-null    datetime64[us]
 8   contratos_vigencia_fim        162 non-null    datetime64[us]
 9   contratos_valor_parcela       162 non-null    float64
 10  contratos_prorrogavel         162 non-null    str
 11  ID do Contrato                162 non-null    int64
 12  contratos_vigencia_contrato   162 non-null    int32
 13  contratos_valor_global        162 non-null    float64
dtypes: datetime64[us](2), float64(2), int32(1), int64(1), str(8)
memory usage: 17.2 KB

In [8]:
# salvar substituindo a base de dados tratada no arquivo existente com o mesmo nome

base_contratos.to_excel('base_contratos_2026_0.1_tratada.xlsx', sheet_name='Contratos', index=False)