In [1]:
import pandas as pd

In [2]:
empenhos_comprasnet = pd.read_excel('empenhos_comprasnet.xlsx', header=1)
display(empenhos_comprasnet.head(3))
empenhos_comprasnet.info()

,Número do instrumento,Fornecedor,Objeto,Número Empenho,Plano Interno,Natureza Despesa,Empenhado,a Liquidar,Liquidado,Pago,RP Inscrito,RP a Liquidar,RP Liquidado,RP Pago,Atualizado Em
0,00029/2022,08.617.414/0001-76 - DFE SEGURANCA ESPECIALIZA...,CONTRATAÇÃO DE EMPRESA ESPECIALIZADA NA PRESTA...,2023NE000073,AGU0032 - SERVICOS DE VIGILANCIA,339039 - OUTROS SERVICOS DE TERCEIROS - PESSOA...,"R$ 558.907,41","R$ 51.064,26","R$ 4.242,13","R$ 503.601,02","R$ 51.064,26","R$ 0,00","R$ 4.262,52","R$ 51.043,87",29/04/2026 07:34:58
1,00029/2022,08.617.414/0001-76 - DFE SEGURANCA ESPECIALIZA...,CONTRATAÇÃO DE EMPRESA ESPECIALIZADA NA PRESTA...,2022NE000340,AGU0032 - SERVICOS DE VIGILANCIA,339039 - OUTROS SERVICOS DE TERCEIROS - PESSOA...,"R$ 169.365,88","R$ 0,00","R$ 4.091,34","R$ 122.933,07","R$ 42.341,47","R$ 0,00","R$ 0,00","R$ 46.432,81",29/04/2026 07:34:58
2,00029/2022,08.617.414/0001-76 - DFE SEGURANCA ESPECIALIZA...,CONTRATAÇÃO DE EMPRESA ESPECIALIZADA NA PRESTA...,2025NE000209,AGU0032 - SERVICOS DE VIGILANCIA,339093 - INDENIZACOES E RESTITUICOES,"R$ 35.311,78","R$ 0,00","R$ 0,00","R$ 35.311,78","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00",29/04/2026 07:34:58

<class 'pandas.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Número do instrumento  2823 non-null   str
 1   Fornecedor             2823 non-null   str
 2   Objeto                 2823 non-null   str
 3   Número Empenho         2823 non-null   str
 4   Plano Interno          2823 non-null   str
 5   Natureza Despesa       2823 non-null   str
 6   Empenhado              2823 non-null   str
 7   a Liquidar             2823 non-null   str
 8   Liquidado              2823 non-null   str
 9   Pago                   2823 non-null   str
 10  RP Inscrito            2823 non-null   str
 11  RP a Liquidar          2823 non-null   str
 12  RP Liquidado           2823 non-null   str
 13  RP Pago                2823 non-null   str
 14  Atualizado Em          2823 non-null   str
dtypes: str(15)
memory usage: 330.9 KB

In [3]:
# excluindo os espaçõs desnecessários no começo e final das colunas de texto
empenhos_comprasnet = empenhos_comprasnet.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [4]:
excluir_colunas = [
    'Atualizado Em'
]
empenhos_comprasnet = empenhos_comprasnet.drop(columns= excluir_colunas)

display(empenhos_comprasnet.head(3))
empenhos_comprasnet.info()

,Número do instrumento,Fornecedor,Objeto,Número Empenho,Plano Interno,Natureza Despesa,Empenhado,a Liquidar,Liquidado,Pago,RP Inscrito,RP a Liquidar,RP Liquidado,RP Pago
0,00029/2022,08.617.414/0001-76 - DFE SEGURANCA ESPECIALIZA...,CONTRATAÇÃO DE EMPRESA ESPECIALIZADA NA PRESTA...,2023NE000073,AGU0032 - SERVICOS DE VIGILANCIA,339039 - OUTROS SERVICOS DE TERCEIROS - PESSOA...,"R$ 558.907,41","R$ 51.064,26","R$ 4.242,13","R$ 503.601,02","R$ 51.064,26","R$ 0,00","R$ 4.262,52","R$ 51.043,87"
1,00029/2022,08.617.414/0001-76 - DFE SEGURANCA ESPECIALIZA...,CONTRATAÇÃO DE EMPRESA ESPECIALIZADA NA PRESTA...,2022NE000340,AGU0032 - SERVICOS DE VIGILANCIA,339039 - OUTROS SERVICOS DE TERCEIROS - PESSOA...,"R$ 169.365,88","R$ 0,00","R$ 4.091,34","R$ 122.933,07","R$ 42.341,47","R$ 0,00","R$ 0,00","R$ 46.432,81"
2,00029/2022,08.617.414/0001-76 - DFE SEGURANCA ESPECIALIZA...,CONTRATAÇÃO DE EMPRESA ESPECIALIZADA NA PRESTA...,2025NE000209,AGU0032 - SERVICOS DE VIGILANCIA,339093 - INDENIZACOES E RESTITUICOES,"R$ 35.311,78","R$ 0,00","R$ 0,00","R$ 35.311,78","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00"

<class 'pandas.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Número do instrumento  2823 non-null   str
 1   Fornecedor             2823 non-null   str
 2   Objeto                 2823 non-null   str
 3   Número Empenho         2823 non-null   str
 4   Plano Interno          2823 non-null   str
 5   Natureza Despesa       2823 non-null   str
 6   Empenhado              2823 non-null   str
 7   a Liquidar             2823 non-null   str
 8   Liquidado              2823 non-null   str
 9   Pago                   2823 non-null   str
 10  RP Inscrito            2823 non-null   str
 11  RP a Liquidar          2823 non-null   str
 12  RP Liquidado           2823 non-null   str
 13  RP Pago                2823 non-null   str
dtypes: str(14)
memory usage: 308.9 KB

In [5]:
renomear_colunas = {
    'Número do instrumento': 'num_instrumento',
    'Fornecedor': 'favorecido',
    'Objeto': 'objeto',
    'Número Empenho': 'num_empenho',
    'Plano Interno': 'plano_interno',
    'Natureza Despesa': 'natureza_despesa',
    'Empenhado': 'empenhado',
    'a Liquidar': 'a_liquidar',
    'Liquidado': 'liquidado',
    'Pago': 'pago',
    'RP Inscrito': 'RP_inscrito',
    'RP a Liquidar': 'RP_a_liquidar',
    'RP Liquidado': 'RP_liquidado',
    'RP Pago': 'RP_pago'
}
empenhos_comprasnet = empenhos_comprasnet.rename(columns= renomear_colunas)

display(empenhos_comprasnet.head(5))
empenhos_comprasnet.info()

,num_instrumento,favorecido,objeto,num_empenho,plano_interno,natureza_despesa,empenhado,a_liquidar,liquidado,pago,RP_inscrito,RP_a_liquidar,RP_liquidado,RP_pago
0,00029/2022,08.617.414/0001-76 - DFE SEGURANCA ESPECIALIZA...,CONTRATAÇÃO DE EMPRESA ESPECIALIZADA NA PRESTA...,2023NE000073,AGU0032 - SERVICOS DE VIGILANCIA,339039 - OUTROS SERVICOS DE TERCEIROS - PESSOA...,"R$ 558.907,41","R$ 51.064,26","R$ 4.242,13","R$ 503.601,02","R$ 51.064,26","R$ 0,00","R$ 4.262,52","R$ 51.043,87"
1,00029/2022,08.617.414/0001-76 - DFE SEGURANCA ESPECIALIZA...,CONTRATAÇÃO DE EMPRESA ESPECIALIZADA NA PRESTA...,2022NE000340,AGU0032 - SERVICOS DE VIGILANCIA,339039 - OUTROS SERVICOS DE TERCEIROS - PESSOA...,"R$ 169.365,88","R$ 0,00","R$ 4.091,34","R$ 122.933,07","R$ 42.341,47","R$ 0,00","R$ 0,00","R$ 46.432,81"
2,00029/2022,08.617.414/0001-76 - DFE SEGURANCA ESPECIALIZA...,CONTRATAÇÃO DE EMPRESA ESPECIALIZADA NA PRESTA...,2025NE000209,AGU0032 - SERVICOS DE VIGILANCIA,339093 - INDENIZACOES E RESTITUICOES,"R$ 35.311,78","R$ 0,00","R$ 0,00","R$ 35.311,78","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00"
3,00029/2022,08.617.414/0001-76 - DFE SEGURANCA ESPECIALIZA...,CONTRATAÇÃO DE EMPRESA ESPECIALIZADA NA PRESTA...,2024NE000037,AGU0032 - SERVICOS DE VIGILANCIA,339039 - OUTROS SERVICOS DE TERCEIROS - PESSOA...,"R$ 254.821,21","R$ 0,00","R$ 0,00","R$ 254.821,21","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00"
4,00029/2022,08.617.414/0001-76 - DFE SEGURANCA ESPECIALIZA...,CONTRATAÇÃO DE EMPRESA ESPECIALIZADA NA PRESTA...,2025NE000318,AGU0032 - SERVICOS DE VIGILANCIA,339039 - OUTROS SERVICOS DE TERCEIROS - PESSOA...,"R$ 14.973,01","R$ 0,00","R$ 0,00","R$ 14.973,01","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00"

<class 'pandas.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   num_instrumento   2823 non-null   str
 1   favorecido        2823 non-null   str
 2   objeto            2823 non-null   str
 3   num_empenho       2823 non-null   str
 4   plano_interno     2823 non-null   str
 5   natureza_despesa  2823 non-null   str
 6   empenhado         2823 non-null   str
 7   a_liquidar        2823 non-null   str
 8   liquidado         2823 non-null   str
 9   pago              2823 non-null   str
 10  RP_inscrito       2823 non-null   str
 11  RP_a_liquidar     2823 non-null   str
 12  RP_liquidado      2823 non-null   str
 13  RP_pago           2823 non-null   str
dtypes: str(14)
memory usage: 308.9 KB

In [6]:
empenhos_comprasnet = empenhos_comprasnet[empenhos_comprasnet['num_empenho'].str.startswith(('2025', '2026'))]

display(empenhos_comprasnet)
empenhos_comprasnet.info()

,num_instrumento,favorecido,objeto,num_empenho,plano_interno,natureza_despesa,empenhado,a_liquidar,liquidado,pago,RP_inscrito,RP_a_liquidar,RP_liquidado,RP_pago
2,00029/2022,08.617.414/0001-76 - DFE SEGURANCA ESPECIALIZA...,CONTRATAÇÃO DE EMPRESA ESPECIALIZADA NA PRESTA...,2025NE000209,AGU0032 - SERVICOS DE VIGILANCIA,339093 - INDENIZACOES E RESTITUICOES,"R$ 35.311,78","R$ 0,00","R$ 0,00","R$ 35.311,78","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00"
4,00029/2022,08.617.414/0001-76 - DFE SEGURANCA ESPECIALIZA...,CONTRATAÇÃO DE EMPRESA ESPECIALIZADA NA PRESTA...,2025NE000318,AGU0032 - SERVICOS DE VIGILANCIA,339039 - OUTROS SERVICOS DE TERCEIROS - PESSOA...,"R$ 14.973,01","R$ 0,00","R$ 0,00","R$ 14.973,01","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00"
22,00035/2024,86.960.598/0001-86 - NORTH SEGURANCA LTDA,SERVIÇOS DE CONTÍNUOS DE VIGILÂNCIA ORGÂNICA A...,2025NE000066,AGU0032 - SERVICOS DE VIGILANCIA,339039 - OUTROS SERVICOS DE TERCEIROS - PESSOA...,"R$ 300.966,80","R$ 0,00","R$ 0,00","R$ 300.966,80","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00"
27,00034/2022,54.222.401/0001-15 - ELEVADORES VILLARTA LTDA,SERVIÇOS DE MANUTENÇÃO EM ELEVADORES DO PRÉDIO...,2025NE000086,AGU0045 - MANUTENCAO DE ELEVADORES,339039 - OUTROS SERVICOS DE TERCEIROS - PESSOA...,"R$ 11.726,75","R$ 11.726,75","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00"
39,00065/2024,13.017.462/0001-63 - ENERGISA SERGIPE - DISTRI...,FORNECIMENTO DE ENERGIA ELETRICA PARA AS UNIDA...,2025NE000245,AGU0052 - SERVICOS DE ENERGIA ELETRICA,339047 - OBRIGACOES TRIBUTARIAS E CONTRIBUTIVAS,"R$ 6.164,09","R$ 897,00","R$ 0,00","R$ 5.267,09","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2814,00030/2022,34.016.448/0001-15 - PROJETCONS ENGENHARIA E A...,O OBJETO DO PRESENTE INSTRUMENTO É A CONTRATAÇ...,2025NE000448,AGU0059 - MANUTENCAO E CONSERVACAO PREDIAL,339039 - OUTROS SERVICOS DE TERCEIROS - PESSOA...,"R$ 16.180,00","R$ 16.180,00","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00"
2815,00025/2023,19.104.617/0001-85 - CARDOSO E AGUIAR COMERCIO...,MANUTENÇÃO PREVENTIVA E CORRETIVA EM APARELHOS...,2025NE000431,AGU0031 - MANUTENCAO DE AR-CONDICIONADO,339039 - OUTROS SERVICOS DE TERCEIROS - PESSOA...,"R$ 14.493,32","R$ 14.493,32","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00"
2818,00025/2023,19.104.617/0001-85 - CARDOSO E AGUIAR COMERCIO...,MANUTENÇÃO PREVENTIVA E CORRETIVA EM APARELHOS...,2025NE000051,AGU0031 - MANUTENCAO DE AR-CONDICIONADO,339039 - OUTROS SERVICOS DE TERCEIROS - PESSOA...,"R$ 29.208,49","R$ 8.155,82","R$ 150,96","R$ 20.901,71","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00"
2819,00025/2023,19.104.617/0001-85 - CARDOSO E AGUIAR COMERCIO...,MANUTENÇÃO PREVENTIVA E CORRETIVA EM APARELHOS...,2026NE000050,AGU0031 - MANUTENCAO DE AR-CONDICIONADO,339039 - OUTROS SERVICOS DE TERCEIROS - PESSOA...,"R$ 9.380,84","R$ 9.380,84","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00"
2821,00039/2024,30.334.799/0001-13 - RC ENGENHARIA E SOLUCOES ...,CONTRATAÇÃO DE SERVIÇOS COMUNS DE ENGENHARIA D...,2025NE000156,AGU0059 - MANUTENCAO E CONSERVACAO PREDIAL,339039 - OUTROS SERVICOS DE TERCEIROS - PESSOA...,"R$ 208.898,47","R$ 72.163,33","R$ 16.006,99","R$ 120.728,15","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00"

<class 'pandas.DataFrame'>
Index: 609 entries, 2 to 2821
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   num_instrumento   609 non-null    str
 1   favorecido        609 non-null    str
 2   objeto            609 non-null    str
 3   num_empenho       609 non-null    str
 4   plano_interno     609 non-null    str
 5   natureza_despesa  609 non-null    str
 6   empenhado         609 non-null    str
 7   a_liquidar        609 non-null    str
 8   liquidado         609 non-null    str
 9   pago              609 non-null    str
 10  RP_inscrito       609 non-null    str
 11  RP_a_liquidar     609 non-null    str
 12  RP_liquidado      609 non-null    str
 13  RP_pago           609 non-null    str
dtypes: str(14)
memory usage: 71.4 KB

In [7]:
'''empenhos_comprasnet['empenhado', 'a_liquidar', 'liquidado', 'pago', 'RP_inscrito', 'RP_a_liquidar', 'RP_liquidado', 'RP_pago'] = pd.to_numeric(
    empenhos_comprasnet['empenhado', 'a_liquidar', 'liquidado', 'pago', 'RP_inscrito', 'RP_a_liquidar', 'RP_liquidado', 'RP_pago']
    .astype(str)
    .str.replace('R$', '', regex=False)
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
    .str.strip(),
    errors='coerce'
)'''

'''colunas_float = [
    'empenhado', 'a_liquidar', 'liquidado', 'pago',
    'RP_inscrito', 'RP_a_liquidar', 'RP_liquidado', 'RP_pago'
]

'mpenhos_comprasnet[colunas_float] = empenhos_comprasnet[colunas_float].apply(
    lambda col: pd.to_numeric(
        col.astype(str)
           .str.replace('R$', '', regex=False)
           .str.replace('.', '', regex=False)
           .str.replace(',', '.', regex=False)
           .str.strip(),
        errors='coerce'
    )
)'''

colunas_float = [
    'empenhado', 'a_liquidar', 'liquidado', 'pago',
    'RP_inscrito', 'RP_a_liquidar', 'RP_liquidado', 'RP_pago'
]

empenhos_comprasnet[colunas_float] = (
    empenhos_comprasnet[colunas_float]
    .replace({'R\\$': '', '\\.': '', ',': '.'}, regex=True)
    .astype(float)
)



display(empenhos_comprasnet.head(5))
empenhos_comprasnet.info()

,num_instrumento,favorecido,objeto,num_empenho,plano_interno,natureza_despesa,empenhado,a_liquidar,liquidado,pago,RP_inscrito,RP_a_liquidar,RP_liquidado,RP_pago
2,00029/2022,08.617.414/0001-76 - DFE SEGURANCA ESPECIALIZA...,CONTRATAÇÃO DE EMPRESA ESPECIALIZADA NA PRESTA...,2025NE000209,AGU0032 - SERVICOS DE VIGILANCIA,339093 - INDENIZACOES E RESTITUICOES,35311.78,0.00,0.0,35311.78,0.0,0.0,0.0,0.0
4,00029/2022,08.617.414/0001-76 - DFE SEGURANCA ESPECIALIZA...,CONTRATAÇÃO DE EMPRESA ESPECIALIZADA NA PRESTA...,2025NE000318,AGU0032 - SERVICOS DE VIGILANCIA,339039 - OUTROS SERVICOS DE TERCEIROS - PESSOA...,14973.01,0.00,0.0,14973.01,0.0,0.0,0.0,0.0
22,00035/2024,86.960.598/0001-86 - NORTH SEGURANCA LTDA,SERVIÇOS DE CONTÍNUOS DE VIGILÂNCIA ORGÂNICA A...,2025NE000066,AGU0032 - SERVICOS DE VIGILANCIA,339039 - OUTROS SERVICOS DE TERCEIROS - PESSOA...,300966.80,0.00,0.0,300966.80,0.0,0.0,0.0,0.0
27,00034/2022,54.222.401/0001-15 - ELEVADORES VILLARTA LTDA,SERVIÇOS DE MANUTENÇÃO EM ELEVADORES DO PRÉDIO...,2025NE000086,AGU0045 - MANUTENCAO DE ELEVADORES,339039 - OUTROS SERVICOS DE TERCEIROS - PESSOA...,11726.75,11726.75,0.0,0.00,0.0,0.0,0.0,0.0
39,00065/2024,13.017.462/0001-63 - ENERGISA SERGIPE - DISTRI...,FORNECIMENTO DE ENERGIA ELETRICA PARA AS UNIDA...,2025NE000245,AGU0052 - SERVICOS DE ENERGIA ELETRICA,339047 - OBRIGACOES TRIBUTARIAS E CONTRIBUTIVAS,6164.09,897.00,0.0,5267.09,0.0,0.0,0.0,0.0

<class 'pandas.DataFrame'>
Index: 609 entries, 2 to 2821
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   num_instrumento   609 non-null    str
 1   favorecido        609 non-null    str
 2   objeto            609 non-null    str
 3   num_empenho       609 non-null    str
 4   plano_interno     609 non-null    str
 5   natureza_despesa  609 non-null    str
 6   empenhado         609 non-null    float64
 7   a_liquidar        609 non-null    float64
 8   liquidado         609 non-null    float64
 9   pago              609 non-null    float64
 10  RP_inscrito       609 non-null    float64
 11  RP_a_liquidar     609 non-null    float64
 12  RP_liquidado      609 non-null    float64
 13  RP_pago           609 non-null    float64
dtypes: float64(8), str(6)
memory usage: 71.4 KB

In [8]:
# salvar em excel
empenhos_comprasnet.to_excel('empenhos_comprasnet_tratada.xlsx', sheet_name = 'empenhos', index=False)