In [1]:
import pandas as pd

In [2]:
empenhos_emitidos = pd.read_excel('empenhos_emitidos.xlsx', header = 2)
display(empenhos_emitidos.head(3))
empenhos_emitidos.info()

c:\Users\luis.henrique\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,NE CCor,NE CCor - Favorecido,Unnamed: 2,NE - Natureza Despesa,Unnamed: 4,NE - PI,Unnamed: 6,NE - PTRES,Ano Lançamento,Saldo - Moeda Origem (Conta Contábil)
0,110096000012025NE000001,110096,SUPERINTENDENCIA REG. DE ADMIN. DA 5ª REGIAO,339039,OUTROS SERVICOS DE TERCEIROS - PESSOA JURIDICA,AGU005H,DESPESAS PROCESSUAIS - HONORARIOS,204003,2025,270000.00
1,110096000012025NE000002,110096,SUPERINTENDENCIA REG. DE ADMIN. DA 5ª REGIAO,339039,OUTROS SERVICOS DE TERCEIROS - PESSOA JURIDICA,AGU005C,DESPESAS PROCESSUAIS - CUSTAS,204003,2025,30000.00
2,110096000012025NE000003,5978261000102,ER COMERCIO E SERVICOS DE FILTROS E REFRIGERAC...,339039,OUTROS SERVICOS DE TERCEIROS - PESSOA JURIDICA,AGU0039,OUTRAS DESPESAS DE TERCEIROS,228607,2025,8635.89

<class 'pandas.DataFrame'>
RangeIndex: 774 entries, 0 to 773
Data columns (total 10 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   NE CCor                                774 non-null    str
 1   NE CCor - Favorecido                   774 non-null    int64
 2   Unnamed: 2                             774 non-null    str
 3   NE - Natureza Despesa                  774 non-null    int64
 4   Unnamed: 4                             774 non-null    str
 5   NE - PI                                774 non-null    str
 6   Unnamed: 6                             774 non-null    str
 7   NE - PTRES                             774 non-null    int64
 8   Ano Lançamento                         774 non-null    int64
 9   Saldo - Moeda Origem (Conta Contábil)  774 non-null    float64
dtypes: float64(1), int64(4), str(5)
memory usage: 60.6 KB

In [3]:
# excluindo os espaçõs desnecessários no começo e final das colunas de texto
empenhos_emitidos = empenhos_emitidos.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [4]:
excluir_colunas = ['NE - PTRES']
empenhos_emitidos = empenhos_emitidos.drop(columns = excluir_colunas)
display(empenhos_emitidos)

,NE CCor,NE CCor - Favorecido,Unnamed: 2,NE - Natureza Despesa,Unnamed: 4,NE - PI,Unnamed: 6,Ano Lançamento,Saldo - Moeda Origem (Conta Contábil)
0,110096000012025NE000001,110096,SUPERINTENDENCIA REG. DE ADMIN. DA 5ª REGIAO,339039,OUTROS SERVICOS DE TERCEIROS - PESSOA JURIDICA,AGU005H,DESPESAS PROCESSUAIS - HONORARIOS,2025,270000.00
1,110096000012025NE000002,110096,SUPERINTENDENCIA REG. DE ADMIN. DA 5ª REGIAO,339039,OUTROS SERVICOS DE TERCEIROS - PESSOA JURIDICA,AGU005C,DESPESAS PROCESSUAIS - CUSTAS,2025,30000.00
2,110096000012025NE000003,5978261000102,ER COMERCIO E SERVICOS DE FILTROS E REFRIGERAC...,339039,OUTROS SERVICOS DE TERCEIROS - PESSOA JURIDICA,AGU0039,OUTRAS DESPESAS DE TERCEIROS,2025,8635.89
3,110096000012025NE000004,2365566000142,TIGRE - SERVICOS GERAIS LTDA,339039,OUTROS SERVICOS DE TERCEIROS - PESSOA JURIDICA,AGU0032,SERVICOS DE VIGILANCIA,2025,11227.10
4,110096000012025NE000005,1364305461,LUCIANO GOMES DE SOUZA,339030,MATERIAL DE CONSUMO,AGU0036,SUPRIMENTO DE FUNDOS,2025,1949.00
...,...,...,...,...,...,...,...,...,...
769,110096000012026NE000304,18200565000188,NEUTRON SEGURANCA PRIVADA LTDA,339039,OUTROS SERVICOS DE TERCEIROS - PESSOA JURIDICA,'-8,SEM INFORMACAO,2026,21830.17
770,110096000012026NE000305,2096772443,HELDER FALCAO TORRES,339030,MATERIAL DE CONSUMO,AGU0036,SUPRIMENTO DE FUNDOS,2026,50.00
771,110096000012026NE000306,73986100334,ADRIANE RODRIGUES DE ALMEIDA,339039,OUTROS SERVICOS DE TERCEIROS - PESSOA JURIDICA,AGU0036,SUPRIMENTO DE FUNDOS,2026,310.00
772,110096000012026NE000307,14588818000181,COPIADORA UNIVERSITARIA LTDA,339039,OUTROS SERVICOS DE TERCEIROS - PESSOA JURIDICA,REDE,REDE DE COLETA,2026,24600.76
773,110096000012026NE000308,11487259000125,PORTAL DA AMAZONIA EMPREENDIMENTOS TURISTICOS ...,339093,INDENIZACOES E RESTITUICOES,AGU0027,LOCACAO DE IMOVEIS,2026,2931.00

In [5]:
renomear_colunas = {
    'NE CCor': 'empenho',
    'NE CCor - Favorecido': 'doc_favorecido',
    'Unnamed: 2': 'nome_favorecido',
    'NE - Natureza Despesa': 'cod_natu_despesa',
    'Unnamed: 4': 'natureza_despesa',
    'NE - PI': 'cod_plano_interno',
    'Unnamed: 6': 'nome_plano_interno',
    'Ano Lançamento': 'ano_lancamento',
    'Saldo - Moeda Origem (Conta Contábil)': 'saldo_moeda'
}
empenhos_emitidos = empenhos_emitidos.rename(columns=renomear_colunas)
display(empenhos_emitidos)
empenhos_emitidos.info()

,empenho,doc_favorecido,nome_favorecido,cod_natu_despesa,natureza_despesa,cod_plano_interno,nome_plano_interno,ano_lancamento,saldo_moeda
0,110096000012025NE000001,110096,SUPERINTENDENCIA REG. DE ADMIN. DA 5ª REGIAO,339039,OUTROS SERVICOS DE TERCEIROS - PESSOA JURIDICA,AGU005H,DESPESAS PROCESSUAIS - HONORARIOS,2025,270000.00
1,110096000012025NE000002,110096,SUPERINTENDENCIA REG. DE ADMIN. DA 5ª REGIAO,339039,OUTROS SERVICOS DE TERCEIROS - PESSOA JURIDICA,AGU005C,DESPESAS PROCESSUAIS - CUSTAS,2025,30000.00
2,110096000012025NE000003,5978261000102,ER COMERCIO E SERVICOS DE FILTROS E REFRIGERAC...,339039,OUTROS SERVICOS DE TERCEIROS - PESSOA JURIDICA,AGU0039,OUTRAS DESPESAS DE TERCEIROS,2025,8635.89
3,110096000012025NE000004,2365566000142,TIGRE - SERVICOS GERAIS LTDA,339039,OUTROS SERVICOS DE TERCEIROS - PESSOA JURIDICA,AGU0032,SERVICOS DE VIGILANCIA,2025,11227.10
4,110096000012025NE000005,1364305461,LUCIANO GOMES DE SOUZA,339030,MATERIAL DE CONSUMO,AGU0036,SUPRIMENTO DE FUNDOS,2025,1949.00
...,...,...,...,...,...,...,...,...,...
769,110096000012026NE000304,18200565000188,NEUTRON SEGURANCA PRIVADA LTDA,339039,OUTROS SERVICOS DE TERCEIROS - PESSOA JURIDICA,'-8,SEM INFORMACAO,2026,21830.17
770,110096000012026NE000305,2096772443,HELDER FALCAO TORRES,339030,MATERIAL DE CONSUMO,AGU0036,SUPRIMENTO DE FUNDOS,2026,50.00
771,110096000012026NE000306,73986100334,ADRIANE RODRIGUES DE ALMEIDA,339039,OUTROS SERVICOS DE TERCEIROS - PESSOA JURIDICA,AGU0036,SUPRIMENTO DE FUNDOS,2026,310.00
772,110096000012026NE000307,14588818000181,COPIADORA UNIVERSITARIA LTDA,339039,OUTROS SERVICOS DE TERCEIROS - PESSOA JURIDICA,REDE,REDE DE COLETA,2026,24600.76
773,110096000012026NE000308,11487259000125,PORTAL DA AMAZONIA EMPREENDIMENTOS TURISTICOS ...,339093,INDENIZACOES E RESTITUICOES,AGU0027,LOCACAO DE IMOVEIS,2026,2931.00

<class 'pandas.DataFrame'>
RangeIndex: 774 entries, 0 to 773
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   empenho             774 non-null    str
 1   doc_favorecido      774 non-null    int64
 2   nome_favorecido     774 non-null    str
 3   cod_natu_despesa    774 non-null    int64
 4   natureza_despesa    774 non-null    str
 5   cod_plano_interno   774 non-null    str
 6   nome_plano_interno  774 non-null    str
 7   ano_lancamento      774 non-null    int64
 8   saldo_moeda         774 non-null    float64
dtypes: float64(1), int64(3), str(5)
memory usage: 54.6 KB

In [6]:
empenhos_emitidos.to_excel('empenhos_emitidos_tratada.xlsx', sheet_name='empenhos_emitidos', index=False)