In [1]:
import pandas as pd
import openpyxl
import numpy as np
import datetime

In [2]:
# carregando a base de dados
ob_semanal_5 = pd.read_excel('ordens_bancarias.xlsx', header=2)

# removendo os espaaços desnecessários da base de dados
ob_semanal_5.columns = ob_semanal_5.columns.str.strip()

display(ob_semanal_5.head(2))
ob_semanal_5.info()

c:\Users\luis.henrique\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Documento Hábil,Compr. - Dia Pagamento,Emissão - Mês,OB,Favorecido Doc.,Unnamed: 5,OB - Processo,Doc - Observação,Doc - Valor,OB - Evento,Unnamed: 10,OB - Inscrição 1
0,110096000012023NP000154,29/09/2025,SET/2025,110096000012025OB002976,1.910000e+02,BANCO DO BRASIL SA,00587.001993/2022-15,DEPOSITO EM GARANTIA SEM PAGAMENTO/CONTA VINCU...,"3285,27",531020.0,LIQ.OBRI.PROV.IND.TRABALHISTAS,2022NE000336
1,110096000012023NP000228,26/02/2025,FEV/2025,110096000012025OB000582,1.785668e+13,ENERGIZA ENGENHARIA LTDA,00587.001839/2022-35,PAGAMENTO DAS NOTAS FISCAIS 44 45 EMITIDAS EM ...,"1190,81",531814.0,PGTO CONTAS A PAGAR/FORNECEDOR,2023NE000082

<class 'pandas.DataFrame'>
RangeIndex: 6718 entries, 0 to 6717
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Documento Hábil         4070 non-null   str
 1   Compr. - Dia Pagamento  4482 non-null   str
 2   Emissão - Mês           4570 non-null   str
 3   OB                      5719 non-null   str
 4   Favorecido Doc.         5719 non-null   float64
 5   Unnamed: 5              5719 non-null   str
 6   OB - Processo           5719 non-null   str
 7   Doc - Observação        5719 non-null   str
 8   Doc - Valor             5719 non-null   str
 9   OB - Evento             5719 non-null   float64
 10  Unnamed: 10             5719 non-null   str
 11  OB - Inscrição 1        6718 non-null   str
dtypes: float64(2), str(10)
memory usage: 629.9 KB

In [3]:
# excluindo colunas desnecessárias
ob_semanal_5.drop(columns=['Unnamed: 10'], inplace=True)

display(ob_semanal_5.head(2))
ob_semanal_5.info()

,Documento Hábil,Compr. - Dia Pagamento,Emissão - Mês,OB,Favorecido Doc.,Unnamed: 5,OB - Processo,Doc - Observação,Doc - Valor,OB - Evento,OB - Inscrição 1
0,110096000012023NP000154,29/09/2025,SET/2025,110096000012025OB002976,1.910000e+02,BANCO DO BRASIL SA,00587.001993/2022-15,DEPOSITO EM GARANTIA SEM PAGAMENTO/CONTA VINCU...,"3285,27",531020.0,2022NE000336
1,110096000012023NP000228,26/02/2025,FEV/2025,110096000012025OB000582,1.785668e+13,ENERGIZA ENGENHARIA LTDA,00587.001839/2022-35,PAGAMENTO DAS NOTAS FISCAIS 44 45 EMITIDAS EM ...,"1190,81",531814.0,2023NE000082

<class 'pandas.DataFrame'>
RangeIndex: 6718 entries, 0 to 6717
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Documento Hábil         4070 non-null   str
 1   Compr. - Dia Pagamento  4482 non-null   str
 2   Emissão - Mês           4570 non-null   str
 3   OB                      5719 non-null   str
 4   Favorecido Doc.         5719 non-null   float64
 5   Unnamed: 5              5719 non-null   str
 6   OB - Processo           5719 non-null   str
 7   Doc - Observação        5719 non-null   str
 8   Doc - Valor             5719 non-null   str
 9   OB - Evento             5719 non-null   float64
 10  OB - Inscrição 1        6718 non-null   str
dtypes: float64(2), str(9)
memory usage: 577.5 KB

In [4]:
ob_semanal_5.rename(columns = {
    'Documento Hábil': 'ob_documento_habil',
    'Compr. - Dia Pagamento': 'ob_data_pagamento',
    'Emissão - Mês': 'ob_mes_emissao',
    'OB': 'ob_ordem_pagamento',
    'Favorecido Doc.': 'ob_doc_fornecedor',
    'Unnamed: 5': 'ob_nome_fornecedor',
    'OB - Processo': 'ob_processo_NUP',
    'Doc - Observação': 'ob_observacao',
    'Doc - Valor': 'ob_valor',
    'OB - Evento': 'ob_evento',
    'OB - Inscrição 1': 'ob_empenho',

}, inplace=True)

display(ob_semanal_5.head(5))
ob_semanal_5.info()

,ob_documento_habil,ob_data_pagamento,ob_mes_emissao,ob_ordem_pagamento,ob_doc_fornecedor,ob_nome_fornecedor,ob_processo_NUP,ob_observacao,ob_valor,ob_evento,ob_empenho
0,110096000012023NP000154,29/09/2025,SET/2025,110096000012025OB002976,1.910000e+02,BANCO DO BRASIL SA,00587.001993/2022-15,DEPOSITO EM GARANTIA SEM PAGAMENTO/CONTA VINCU...,"3285,27",531020.0,2022NE000336
1,110096000012023NP000228,26/02/2025,FEV/2025,110096000012025OB000582,1.785668e+13,ENERGIZA ENGENHARIA LTDA,00587.001839/2022-35,PAGAMENTO DAS NOTAS FISCAIS 44 45 EMITIDAS EM ...,"1190,81",531814.0,2023NE000082
2,110096000012023NP000255,26/02/2025,FEV/2025,110096000012025OB000583,1.785668e+13,ENERGIZA ENGENHARIA LTDA,00587.001767/2022-26,"PAGAMENTO DA NOTA FISCAL 98, 16/01/2023 (SERVI...","1315,9",531814.0,2022NE000299
3,110096000012023NP000503,26/02/2025,FEV/2025,110096000012025OB000584,1.785668e+13,ENERGIZA ENGENHARIA LTDA,00587001839/2022-35,"PAGAMENTO DA NOTA FISCAL 263, 15/02/2023, REFE...","178,62",531814.0,2023NE000082
4,110096000012023NP001664,31/10/2025,OUT/2025,110096000012025OB003289,1.910000e+02,BANCO DO BRASIL SA,00587.000190/2023-16,DEPOSITO EM GARANTIA SEM PAGAMENTO/CONTA VINCU...,"426,6",531020.0,2023NE000043

<class 'pandas.DataFrame'>
RangeIndex: 6718 entries, 0 to 6717
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ob_documento_habil  4070 non-null   str
 1   ob_data_pagamento   4482 non-null   str
 2   ob_mes_emissao      4570 non-null   str
 3   ob_ordem_pagamento  5719 non-null   str
 4   ob_doc_fornecedor   5719 non-null   float64
 5   ob_nome_fornecedor  5719 non-null   str
 6   ob_processo_NUP     5719 non-null   str
 7   ob_observacao       5719 non-null   str
 8   ob_valor            5719 non-null   str
 9   ob_evento           5719 non-null   float64
 10  ob_empenho          6718 non-null   str
dtypes: float64(2), str(9)
memory usage: 577.5 KB

In [5]:
# removendo colunas vazias
ob_semanal_5.dropna(axis=1, how='all', inplace=True)

# removendo linhas inválidas
ob_semanal_5 = ob_semanal_5[ob_semanal_5['ob_documento_habil'].notna()]
ob_semanal_5 = ob_semanal_5[ob_semanal_5['ob_documento_habil'] != "'-8"]
ob_semanal_5 = ob_semanal_5[ob_semanal_5['ob_empenho'].notna()]
ob_semanal_5 = ob_semanal_5[ob_semanal_5['ob_empenho'] != "'-8"]

# excluindo os 11 primeiros caracteres da coluna 'ob_documento_habil'
ob_semanal_5['ob_documento_habil'] = ob_semanal_5['ob_documento_habil'].str[11:]
ob_semanal_5['ob_ordem_pagamento'] = ob_semanal_5['ob_ordem_pagamento'].str[11:]
#ob_semanal_5['ob_empenho'] = ob_semanal_5['ob_empenho'].str[11:]

# converter a coluna 'ob_data_pagamento' para o formato datetime
ob_semanal_5['ob_data_pagamento'] = pd.to_datetime(ob_semanal_5['ob_data_pagamento'], errors='coerce')

# Converter 'ob_mes_emissao' - formato português MÊS/YYYY (ex: SET/2025)
# O formato original é em português, como "SET/2025", "FEV/2025", etc.
meses_pt = {
    'JAN': 1, 'FEV': 2, 'MAR': 3, 'ABR': 4, 'MAI': 5, 'JUN': 6,
    'JUL': 7, 'AGO': 8, 'SET': 9, 'OUT': 10, 'NOV': 11, 'DEZ': 12
}

def converter_mes_ano(valor):
    if pd.isna(valor):
        return pd.NaT
    try:
        mes_str, ano_str = str(valor).split('/')
        mes = meses_pt.get(mes_str.upper())
        if mes is None:
            return pd.NaT
        return pd.Timestamp(year=int(ano_str), month=mes, day=1)
    except:
        return pd.NaT

ob_semanal_5['ob_mes_emissao'] = ob_semanal_5['ob_mes_emissao'].apply(converter_mes_ano)

# convertendo a coluna 'ob_evento' para string
ob_semanal_5['ob_evento'] = ob_semanal_5['ob_evento'].astype(str)
ob_semanal_5['ob_doc_fornecedor'] = ob_semanal_5['ob_doc_fornecedor'].astype(str)

# convertendo a coluna 'ob_valor' para tipo float
ob_semanal_5['ob_valor'] = pd.to_numeric(
    ob_semanal_5['ob_valor']
    .astype(str)
    .str.replace('R$', '', regex=False)
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
    .str.strip(),
    errors='coerce'
)

display(ob_semanal_5.head(2))
ob_semanal_5.info()

C:\Users\luis.henrique\AppData\Local\Temp\ipykernel_4748\1797518363.py:16: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  ob_semanal_5['ob_data_pagamento'] = pd.to_datetime(ob_semanal_5['ob_data_pagamento'], errors='coerce')

,ob_documento_habil,ob_data_pagamento,ob_mes_emissao,ob_ordem_pagamento,ob_doc_fornecedor,ob_nome_fornecedor,ob_processo_NUP,ob_observacao,ob_valor,ob_evento,ob_empenho
0,2023NP000154,2025-09-29,2025-09-01,2025OB002976,191.0,BANCO DO BRASIL SA,00587.001993/2022-15,DEPOSITO EM GARANTIA SEM PAGAMENTO/CONTA VINCU...,3285.27,531020.0,2022NE000336
1,2023NP000228,2025-02-26,2025-02-01,2025OB000582,17856676000184.0,ENERGIZA ENGENHARIA LTDA,00587.001839/2022-35,PAGAMENTO DAS NOTAS FISCAIS 44 45 EMITIDAS EM ...,1190.81,531814.0,2023NE000082

<class 'pandas.DataFrame'>
Index: 4070 entries, 0 to 6717
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ob_documento_habil  4070 non-null   str
 1   ob_data_pagamento   4070 non-null   datetime64[us]
 2   ob_mes_emissao      4070 non-null   datetime64[us]
 3   ob_ordem_pagamento  4070 non-null   str
 4   ob_doc_fornecedor   4070 non-null   str
 5   ob_nome_fornecedor  4070 non-null   str
 6   ob_processo_NUP     4070 non-null   str
 7   ob_observacao       4070 non-null   str
 8   ob_valor            4070 non-null   float64
 9   ob_evento           4070 non-null   str
 10  ob_empenho          4070 non-null   str
dtypes: datetime64[us](2), float64(1), str(8)
memory usage: 381.6 KB

In [6]:
ob_semanal_5 = ob_semanal_5[ob_semanal_5['ob_ordem_pagamento'].str.startswith("2026")]

In [7]:
# removendo duplicados
ob_semanal_5.drop_duplicates(inplace=True)
#ob_semanal_5.drop_duplicates(subset=['dh_chave_relacionamento'], inplace=True)

display(ob_semanal_5.head(2))
ob_semanal_5.info()

,ob_documento_habil,ob_data_pagamento,ob_mes_emissao,ob_ordem_pagamento,ob_doc_fornecedor,ob_nome_fornecedor,ob_processo_NUP,ob_observacao,ob_valor,ob_evento,ob_empenho
9,2024NP000060,2026-03-31,2026-03-01,2026OB000863,16698131000124.0,SUPRITECH SOLUCOES AMBIENTAIS LTDA,00587.000198/2023-82,DESCRICAO:PRESTACAO DE SERVICOS CONTINUOS DE L...,4215.70,531814.0,2023NE000060
10,2024NP000061,2026-03-31,2026-03-01,2026OB000861,16698131000124.0,SUPRITECH SOLUCOES AMBIENTAIS LTDA,00587.000253/2023-34,REPASSE DE SALDO DA NOTA FISCAL 1432/EMITIDA ...,77.99,531814.0,2023NE000060

<class 'pandas.DataFrame'>
Index: 1374 entries, 9 to 6717
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ob_documento_habil  1374 non-null   str
 1   ob_data_pagamento   1374 non-null   datetime64[us]
 2   ob_mes_emissao      1374 non-null   datetime64[us]
 3   ob_ordem_pagamento  1374 non-null   str
 4   ob_doc_fornecedor   1374 non-null   str
 5   ob_nome_fornecedor  1374 non-null   str
 6   ob_processo_NUP     1374 non-null   str
 7   ob_observacao       1374 non-null   str
 8   ob_valor            1374 non-null   float64
 9   ob_evento           1374 non-null   str
 10  ob_empenho          1374 non-null   str
dtypes: datetime64[us](2), float64(1), str(8)
memory usage: 128.8 KB

In [8]:
#ob_semanal_5 = ob_semanal_5[ob_semanal_5['ob_empenho'].astype(str).str.startswith(('2023','2024', '2025', '2026'), na=False)]
display(ob_semanal_5)
ob_semanal_5.info()

,ob_documento_habil,ob_data_pagamento,ob_mes_emissao,ob_ordem_pagamento,ob_doc_fornecedor,ob_nome_fornecedor,ob_processo_NUP,ob_observacao,ob_valor,ob_evento,ob_empenho
9,2024NP000060,2026-03-31,2026-03-01,2026OB000863,16698131000124.0,SUPRITECH SOLUCOES AMBIENTAIS LTDA,00587.000198/2023-82,DESCRICAO:PRESTACAO DE SERVICOS CONTINUOS DE L...,4215.70,531814.0,2023NE000060
10,2024NP000061,2026-03-31,2026-03-01,2026OB000861,16698131000124.0,SUPRITECH SOLUCOES AMBIENTAIS LTDA,00587.000253/2023-34,REPASSE DE SALDO DA NOTA FISCAL 1432/EMITIDA ...,77.99,531814.0,2023NE000060
12,2024NP000715,2026-03-27,2026-03-01,2026OB000845,19389810000100.0,AHIH SERVICOS E CONSULTORIA LTDA,00415.007048/2024-52,"PAGAMENTO DA NOTA FISCAL 1001091, EMITIDA EM 1...",953.08,531814.0,2024NE000061
16,2024NP001422,2026-06-30,2026-06-01,2026OB001824,15150504000165.0,LDS SERVICOS DE LIMPEZA LTDA,00415.076853/2024-26,"LIQUIDACAO E PAGAMENTO DA NOTA FISCAL 10880, D...",1364.16,531814.0,2024NE000233
52,2024NP002504,2026-03-26,2026-03-01,2026OB000834,191.0,BANCO DO BRASIL SA,90802.000018/2024-44,PAGAMENTO EM CONTA VINCULADA DA NF. 0157 E 159...,7504.84,531020.0,2024NE000166
...,...,...,...,...,...,...,...,...,...,...,...
6713,2026RP000164,2026-07-17,2026-07-01,2026OB002039,5258972000102.0,PARMENIO EMPREENDIMENTOS IMOBILIARIOS LTDA,01199.000016/2026-52,"PGTO DO RECIBO 705170 01JUL26, REF. JUN/26...",32511.52,531814.0,2026NE000214
6714,2026RP000165,2026-07-22,2026-07-01,2026OB002081,11487259000125.0,PORTAL DA AMAZONIA EMPREENDIMENTOS TURISTICOS ...,01199.000015/2026-16,"LIQUIDACAO E PAGAMENTO DO RECIBO 06/2026,EMITI...",17687.13,531814.0,2026NE000298
6715,2026RP000166,2026-07-21,2026-07-01,2026OB002059,13938116000118.0,ANCAR - ADMINISTRADORES DE IMOVEIS E DE CONDOM...,90803.000005/2026-27,"PAGAMENTO DA NF 400 REF JUNHO/2026,DE 01/07/2...",14271.11,531814.0,2026NE000021
6716,2026RP000167,2026-07-22,2026-07-01,2026OB002077,8475436000149.0,MONTANA CONSTRUCOES LTDA,00587.000862/2026-36,"PAGAMENTO DO RECIBO DE NUMEO 06/2026,DE 01/07/...",86850.84,531814.0,2026NE000028
6717,2026RP000168,2026-07-23,2026-07-01,2026OB002109,11487259000125.0,PORTAL DA AMAZONIA EMPREENDIMENTOS TURISTICOS ...,01199.000015/2026-16,"LIQUIDACAO DA NOTA DE COBRANCA S/N, EMITIDA EM...",2931.00,531814.0,2026NE000308

<class 'pandas.DataFrame'>
Index: 1374 entries, 9 to 6717
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ob_documento_habil  1374 non-null   str
 1   ob_data_pagamento   1374 non-null   datetime64[us]
 2   ob_mes_emissao      1374 non-null   datetime64[us]
 3   ob_ordem_pagamento  1374 non-null   str
 4   ob_doc_fornecedor   1374 non-null   str
 5   ob_nome_fornecedor  1374 non-null   str
 6   ob_processo_NUP     1374 non-null   str
 7   ob_observacao       1374 non-null   str
 8   ob_valor            1374 non-null   float64
 9   ob_evento           1374 non-null   str
 10  ob_empenho          1374 non-null   str
dtypes: datetime64[us](2), float64(1), str(8)
memory usage: 128.8 KB

In [9]:
# salvando a base de dados tratada
ob_semanal_5.to_excel('ordens_bancarias_tratada.xlsx', sheet_name='OB_semanal_5', index=False)