In [1]:
# Importação das Bibliotecas
import pandas as pd # para manipulação de dados
import os # para manipulação de arquivos e diretórios
import shutil # para mover arquivos entre diretórios
import datetime # para manipulação de datas
import calendar # para manipulação de calendários
import numpy as np # para manipulação de arrays e operações matemáticas

In [2]:
# mover um arquivo de uma pasta para outra e renomeá-lo
pasta_origem = r'C:\Users\luis.henrique\Downloads' # caminho do diretório onde está o arquivo Excel
arquivo_excel = 'Empenhos  Contratos.gov.br.xlsx' # nome do arquivo Excel que se deseja ler
pasta_destino = r'C:\Users\luis.henrique\AGU\FileServer-SADPE - Documentos\POWER_BI\Empenhos'  # caminho completo do arquivo Excel
novo_nome_arquivo = 'base_empenhos_2026_0.1_tratada.xlsx' # novo nome do arquivo Excel
caminho_origem = os.path.join(pasta_origem, arquivo_excel) # caminho completo do arquivo Excel de origem
caminho_destino = os.path.join(pasta_destino, novo_nome_arquivo) # caminho completo do arquivo Excel de destino com o novo nome

# verificar se o arquivo Excel existe no diretório de origem
if os.path.exists(caminho_origem):
    shutil.move(caminho_origem, caminho_destino) # mover e renomear o arquivo Excel

# remover da pasta_origem o arquivo Excel
if os.path.exists(caminho_origem):
    os.remove(caminho_origem)

In [3]:
# Carregamento da base de Dados - Empenhos
base_empenhos = pd.read_excel('base_empenhos_2026_0.1_tratada.xlsx', header=1)
#base_empenhos = pd.read_excel('base_empenhos_2026_0.1.xlsx', header=0)
display(base_empenhos.head(2))
base_empenhos.info()

# excluindo todos os espaços desnecessários do início e do fim dos valores das colunas
base_empenhos = base_empenhos.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

,Número do instrumento,Fornecedor,Objeto,Número Empenho,Plano Interno,Empenhado,a Liquidar,Liquidado,Pago,RP Inscrito,RP a Liquidar,RP Liquidado,RP Pago,Atualizado Em
0,00008/2025,08.989.745/0001-37 - CANAA FACILITIES LTDA,"CONTRATAÇÃO DE SERVIÇOS CONTÍNUOS DE LIMPEZA, ...",2025NE000244,AGU0040 - SERVICOS DE LIMPEZA,"R$ 34.971,59","R$ 0,00","R$ 0,00","R$ 34.971,59","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00",29/04/2026 07:34:58
1,00008/2025,08.989.745/0001-37 - CANAA FACILITIES LTDA,"CONTRATAÇÃO DE SERVIÇOS CONTÍNUOS DE LIMPEZA, ...",2025NE000278,AGU0040 - SERVICOS DE LIMPEZA,"R$ 259.662,36","R$ 86.027,43","R$ 4.475,54","R$ 169.159,39","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00",29/04/2026 07:34:58

<class 'pandas.DataFrame'>
RangeIndex: 2762 entries, 0 to 2761
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Número do instrumento  2762 non-null   str
 1   Fornecedor             2762 non-null   str
 2   Objeto                 2762 non-null   str
 3   Número Empenho         2762 non-null   str
 4   Plano Interno          2762 non-null   str
 5   Empenhado              2762 non-null   str
 6   a Liquidar             2762 non-null   str
 7   Liquidado              2762 non-null   str
 8   Pago                   2762 non-null   str
 9   RP Inscrito            2762 non-null   str
 10  RP a Liquidar          2762 non-null   str
 11  RP Liquidado           2762 non-null   str
 12  RP Pago                2762 non-null   str
 13  Atualizado Em          2762 non-null   str
dtypes: str(14)
memory usage: 302.2 KB

In [4]:
# Exclusão de colunas desnecessárias
colunas_excluir = ['Atualizado Em']
base_empenhos = base_empenhos.drop(columns=colunas_excluir)

display(base_empenhos.head(2))
base_empenhos.info()

,Número do instrumento,Fornecedor,Objeto,Número Empenho,Plano Interno,Empenhado,a Liquidar,Liquidado,Pago,RP Inscrito,RP a Liquidar,RP Liquidado,RP Pago
0,00008/2025,08.989.745/0001-37 - CANAA FACILITIES LTDA,"CONTRATAÇÃO DE SERVIÇOS CONTÍNUOS DE LIMPEZA, ...",2025NE000244,AGU0040 - SERVICOS DE LIMPEZA,"R$ 34.971,59","R$ 0,00","R$ 0,00","R$ 34.971,59","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00"
1,00008/2025,08.989.745/0001-37 - CANAA FACILITIES LTDA,"CONTRATAÇÃO DE SERVIÇOS CONTÍNUOS DE LIMPEZA, ...",2025NE000278,AGU0040 - SERVICOS DE LIMPEZA,"R$ 259.662,36","R$ 86.027,43","R$ 4.475,54","R$ 169.159,39","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00"

<class 'pandas.DataFrame'>
RangeIndex: 2762 entries, 0 to 2761
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Número do instrumento  2762 non-null   str
 1   Fornecedor             2762 non-null   str
 2   Objeto                 2762 non-null   str
 3   Número Empenho         2762 non-null   str
 4   Plano Interno          2762 non-null   str
 5   Empenhado              2762 non-null   str
 6   a Liquidar             2762 non-null   str
 7   Liquidado              2762 non-null   str
 8   Pago                   2762 non-null   str
 9   RP Inscrito            2762 non-null   str
 10  RP a Liquidar          2762 non-null   str
 11  RP Liquidado           2762 non-null   str
 12  RP Pago                2762 non-null   str
dtypes: str(13)
memory usage: 280.6 KB

In [5]:
# mudar nome das colunas para facilitar a manipulação
base_empenhos = base_empenhos.rename(columns=
                                       {'Número do instrumento': 'empenhos_num_instrumento',
                                        'Fornecedor': 'empenhos_doc_fornecedor',
                                        'Objeto': 'empenhos_objeto',
                                        'Número Empenho': 'empenhos_num_empenho',
                                        'Plano Interno': 'empenhos_plano_interno',
                                        'Empenhado': 'empenhos_R$_empenhado',
                                        'a Liquidar': 'empenhos_R$_a_liquidar',
                                        'Liquidado': 'empenhos_R$_liquidado',
                                        'Pago': 'empenhos_R$_pago',
                                        'RP Inscrito': 'empenhos_RP_inscrito',
                                        'RP a Liquidar': 'empenhos_RP_a_liquidar',
                                        'RP Liquidado': 'empenhos_RP_liquidado',
                                        'RP Pago': 'empenhos_RP_pago'})

# retirar os pontos e virgulas da coluna cnpj e cpf deixar apenas os números
base_empenhos['empenhos_doc_fornecedor'] = base_empenhos['empenhos_doc_fornecedor'].str.replace('.', '', regex=False).str.replace('-', '', regex=False).str.replace('/', '', regex=False)

#base_empenhos = base_empenhos[base_empenhos['empenhos_num_empenho'].astype(str).str.startswith(('2024', '2025', '2026'), na=False)]

display(base_empenhos.head(2))
base_empenhos.info()

,empenhos_num_instrumento,empenhos_doc_fornecedor,empenhos_objeto,empenhos_num_empenho,empenhos_plano_interno,empenhos_R$_empenhado,empenhos_R$_a_liquidar,empenhos_R$_liquidado,empenhos_R$_pago,empenhos_RP_inscrito,empenhos_RP_a_liquidar,empenhos_RP_liquidado,empenhos_RP_pago
0,00008/2025,08989745000137 CANAA FACILITIES LTDA,"CONTRATAÇÃO DE SERVIÇOS CONTÍNUOS DE LIMPEZA, ...",2025NE000244,AGU0040 - SERVICOS DE LIMPEZA,"R$ 34.971,59","R$ 0,00","R$ 0,00","R$ 34.971,59","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00"
1,00008/2025,08989745000137 CANAA FACILITIES LTDA,"CONTRATAÇÃO DE SERVIÇOS CONTÍNUOS DE LIMPEZA, ...",2025NE000278,AGU0040 - SERVICOS DE LIMPEZA,"R$ 259.662,36","R$ 86.027,43","R$ 4.475,54","R$ 169.159,39","R$ 0,00","R$ 0,00","R$ 0,00","R$ 0,00"

<class 'pandas.DataFrame'>
RangeIndex: 2762 entries, 0 to 2761
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   empenhos_num_instrumento  2762 non-null   str
 1   empenhos_doc_fornecedor   2762 non-null   str
 2   empenhos_objeto           2762 non-null   str
 3   empenhos_num_empenho      2762 non-null   str
 4   empenhos_plano_interno    2762 non-null   str
 5   empenhos_R$_empenhado     2762 non-null   str
 6   empenhos_R$_a_liquidar    2762 non-null   str
 7   empenhos_R$_liquidado     2762 non-null   str
 8   empenhos_R$_pago          2762 non-null   str
 9   empenhos_RP_inscrito      2762 non-null   str
 10  empenhos_RP_a_liquidar    2762 non-null   str
 11  empenhos_RP_liquidado     2762 non-null   str
 12  empenhos_RP_pago          2762 non-null   str
dtypes: str(13)
memory usage: 280.6 KB

In [6]:
'''                                                 
# mudar colunas DE VALORES para float
base_empenhos['R$_Empenhado'] = (
    base_empenhos['R$_Empenhado']
    .astype(str)
    .str.replace(r'[R$\s.]', '', regex=True)  # remove R$, espaços e pontos
    .str.replace(',', '.', regex=False)       # troca vírgula por ponto
)
base_empenhos['R$_Empenhado'] = pd.to_numeric(base_empenhos['R$_Empenhado'], errors='coerce')
base_empenhos['R$_Empenhado'] = base_empenhos['R$_Empenhado']

base_empenhos['R$_a_liquidar'] = (
    base_empenhos['R$_a_liquidar']
    .astype(str)
    .str.replace(r'[R$\s.]', '', regex=True)  # remove R$, espaços e pontos
    .str.replace(',', '.', regex=False)       # troca vírgula por ponto
)
base_empenhos['R$_a_liquidar'] = pd.to_numeric(base_empenhos['R$_a_liquidar'], errors='coerce')
base_empenhos['R$_a_liquidar'] = base_empenhos['R$_a_liquidar']

base_empenhos['R$_Liquidado'] = (
    base_empenhos['R$_Liquidado']
    .astype(str)
    .str.replace(r'[R$\s.]', '', regex=True)  # remove R$, espaços e pontos
    .str.replace(',', '.', regex=False)       # troca vírgula por ponto
)
base_empenhos['R$_Liquidado'] = pd.to_numeric(base_empenhos['R$_Liquidado'], errors='coerce')
base_empenhos['R$_Liquidado'] = base_empenhos['R$_Liquidado']

base_empenhos['R$_Pago'] = (
    base_empenhos['R$_Pago']
    .astype(str)
    .str.replace(r'[R$\s.]', '', regex=True)  # remove R$, espaços e pontos
    .str.replace(',', '.', regex=False)       # troca vírgula por ponto
)
base_empenhos['R$_Pago'] = pd.to_numeric(base_empenhos['R$_Pago'], errors='coerce')
base_empenhos['R$_Pago'] = base_empenhos['R$_Pago']

base_empenhos['RP_Inscrito'] = (
    base_empenhos['RP_Inscrito']
    .astype(str)
    .str.replace(r'[R$\s.]', '', regex=True)  # remove R$, espaços e pontos
    .str.replace(',', '.', regex=False)       # troca vírgula por ponto
)
base_empenhos['RP_Inscrito'] = pd.to_numeric(base_empenhos['RP_Inscrito'], errors='coerce')
base_empenhos['RP_Inscrito'] = base_empenhos['RP_Inscrito']

base_empenhos['RP_a_Liquidar'] = (
    base_empenhos['RP_a_Liquidar']
    .astype(str)
    .str.replace(r'[R$\s.]', '', regex=True)  # remove R$, espaços e pontos
    .str.replace(',', '.', regex=False)       # troca vírgula por ponto
)
base_empenhos['RP_a_Liquidar'] = pd.to_numeric(base_empenhos['RP_a_Liquidar'], errors='coerce')
base_empenhos['RP_a_Liquidar'] = base_empenhos['RP_a_Liquidar']

base_empenhos['RP_Liquidado'] = (
    base_empenhos['RP_Liquidado']
    .astype(str)
    .str.replace(r'[R$\s.]', '', regex=True)  # remove R$, espaços e pontos
    .str.replace(',', '.', regex=False)       # troca vírgula por ponto
)
base_empenhos['RP_Liquidado'] = pd.to_numeric(base_empenhos['RP_Liquidado'], errors='coerce')
base_empenhos['RP_Liquidado'] = base_empenhos['RP_Liquidado']

base_empenhos['RP_Pago'] = (
    base_empenhos['RP_Pago']
    .astype(str)
    .str.replace(r'[R$\s.]', '', regex=True)  # remove R$, espaços e pontos
    .str.replace(',', '.', regex=False)       # troca vírgula por ponto
)
base_empenhos['RP_Pago'] = pd.to_numeric(base_empenhos['RP_Pago'], errors='coerce')
base_empenhos['RP_Pago'] = base_empenhos['RP_Pago']

display(base_empenhos.head(5))
base_empenhos.info()'''

<>:6: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:6: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
C:\Users\luis.henrique\AppData\Local\Temp\ipykernel_8104\2121524158.py:6: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  .str.replace(r'[R$\s.]', '', regex=True)  # remove R$, espaços e pontos

"                                                 \n# mudar colunas DE VALORES para float\nbase_empenhos['R$_Empenhado'] = (\n    base_empenhos['R$_Empenhado']\n    .astype(str)\n    .str.replace(r'[R$\\s.]', '', regex=True)  # remove R$, espaços e pontos\n    .str.replace(',', '.', regex=False)       # troca vírgula por ponto\n)\nbase_empenhos['R$_Empenhado'] = pd.to_numeric(base_empenhos['R$_Empenhado'], errors='coerce')\nbase_empenhos['R$_Empenhado'] = base_empenhos['R$_Empenhado']\n\nbase_empenhos['R$_a_liquidar'] = (\n    base_empenhos['R$_a_liquidar']\n    .astype(str)\n    .str.replace(r'[R$\\s.]', '', regex=True)  # remove R$, espaços e pontos\n    .str.replace(',', '.', regex=False)       # troca vírgula por ponto\n)\nbase_empenhos['R$_a_liquidar'] = pd.to_numeric(base_empenhos['R$_a_liquidar'], errors='coerce')\nbase_empenhos['R$_a_liquidar'] = base_empenhos['R$_a_liquidar']\n\nbase_empenhos['R$_Liquidado'] = (\n    base_empenhos['R$_Liquidado']\n    .astype(str)\n    .str.replace(r'[R$\\s.]', '', regex=True)  # remove R$, espaços e pontos\n    .str.replace(',', '.', regex=False)       # troca vírgula por ponto\n)\nbase_empenhos['R$_Liquidado'] = pd.to_numeric(base_empenhos['R$_Liquidado'], errors='coerce')\nbase_empenhos['R$_Liquidado'] = base_empenhos['R$_Liquidado']\n\nbase_empenhos['R$_Pago'] = (\n    base_empenhos['R$_Pago']\n    .astype(str)\n    .str.replace(r'[R$\\s.]', '', regex=True)  # remove R$, espaços e pontos\n    .str.replace(',', '.', regex=False)       # troca vírgula por ponto\n)\nbase_empenhos['R$_Pago'] = pd.to_numeric(base_empenhos['R$_Pago'], errors='coerce')\nbase_empenhos['R$_Pago'] = base_empenhos['R$_Pago']\n\nbase_empenhos['RP_Inscrito'] = (\n    base_empenhos['RP_Inscrito']\n    .astype(str)\n    .str.replace(r'[R$\\s.]', '', regex=True)  # remove R$, espaços e pontos\n    .str.replace(',', '.', regex=False)       # troca vírgula por ponto\n)\nbase_empenhos['RP_Inscrito'] = pd.to_numeric(base_empenhos['RP_Inscrito'], errors='coerce')\nbase_empenhos['RP_Inscrito'] = base_empenhos['RP_Inscrito']\n\nbase_empenhos['RP_a_Liquidar'] = (\n    base_empenhos['RP_a_Liquidar']\n    .astype(str)\n    .str.replace(r'[R$\\s.]', '', regex=True)  # remove R$, espaços e pontos\n    .str.replace(',', '.', regex=False)       # troca vírgula por ponto\n)\nbase_empenhos['RP_a_Liquidar'] = pd.to_numeric(base_empenhos['RP_a_Liquidar'], errors='coerce')\nbase_empenhos['RP_a_Liquidar'] = base_empenhos['RP_a_Liquidar']\n\nbase_empenhos['RP_Liquidado'] = (\n    base_empenhos['RP_Liquidado']\n    .astype(str)\n    .str.replace(r'[R$\\s.]', '', regex=True)  # remove R$, espaços e pontos\n    .str.replace(',', '.', regex=False)       # troca vírgula por ponto\n)\nbase_empenhos['RP_Liquidado'] = pd.to_numeric(base_empenhos['RP_Liquidado'], errors='coerce')\nbase_empenhos['RP_Liquidado'] = base_empenhos['RP_Liquidado']\n\nbase_empenhos['RP_Pago'] = (\n    base_empenhos['RP_Pago']\n    .astype(str)\n    .str.replace(r'[R$\\s.]', '', regex=True)  # remove R$, espaços e pontos\n    .str.replace(',', '.', regex=False)       # troca vírgula por ponto\n)\nbase_empenhos['RP_Pago'] = pd.to_numeric(base_empenhos['RP_Pago'], errors='coerce')\nbase_empenhos['RP_Pago'] = base_empenhos['RP_Pago']\n\ndisplay(base_empenhos.head(5))\nbase_empenhos.info()"

In [7]:
# salvar substituindo a base de dados tratada no arquivo existente com o mesmo nome

base_empenhos.to_excel('base_empenhos_2026_0.1_tratada.xlsx', sheet_name='Empenhos', index=False)