In [1]:
import pandas as pd
import openpyxl
import numpy as np

In [2]:
# carregando a base de dados
dh_semanal_5 = pd.read_excel('dh_semanal_0.5.xlsx', header=2)

# removendo os espaaços desnecessários da base de dados
dh_semanal_5.columns = dh_semanal_5.columns.str.strip()

display(dh_semanal_5.head(2))
dh_semanal_5.info()

c:\Users\luis.henrique\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Documento Hábil,DH - Doc. Origem,DH - Credor,Unnamed: 3,DH - Mês Emissão,DH - Valor,DH - Observação,DH Item - Nota Empenho,DetaCusto DH - R$
0,110096000012020NP000002,NOV-5412-PSF/CGE,06798516000100,EGEL LOCACAO DE VEICULOS LTDA,JAN/2020,20437.63,LIQUIDAÇÃO DA NF. 5412 DE 04/DEZ/2019 FATURA ...,'-8,20437.63
1,110096000012020NP000003,NOV/3473/CJU-AL,15039942000150,STARLIGHT SERVICE LIMPEZA DE BENS IMOVEIS LTDA,JAN/2020,3166.20,"LIQUIDAÇÃO DA NF 3473, REF À FAT NOV/19 DO CON...",'-8,3166.20

<class 'pandas.DataFrame'>
RangeIndex: 27454 entries, 0 to 27453
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Documento Hábil         23804 non-null  str
 1   DH - Doc. Origem        26045 non-null  str
 2   DH - Credor             26045 non-null  str
 3   Unnamed: 3              26045 non-null  str
 4   DH - Mês Emissão        26045 non-null  str
 5   DH - Valor              26045 non-null  float64
 6   DH - Observação         26045 non-null  str
 7   DH Item - Nota Empenho  27454 non-null  str
 8   DetaCusto DH - R$       27454 non-null  float64
dtypes: float64(2), str(7)
memory usage: 1.9 MB

In [3]:
# excluido colunas desncessárias
dh_semanal_5.drop(columns=['DH - Doc. Origem', 'DetaCusto DH - R$'], inplace=True)

display(dh_semanal_5.head(2))
dh_semanal_5.info()

,Documento Hábil,DH - Credor,Unnamed: 3,DH - Mês Emissão,DH - Valor,DH - Observação,DH Item - Nota Empenho
0,110096000012020NP000002,06798516000100,EGEL LOCACAO DE VEICULOS LTDA,JAN/2020,20437.63,LIQUIDAÇÃO DA NF. 5412 DE 04/DEZ/2019 FATURA ...,'-8
1,110096000012020NP000003,15039942000150,STARLIGHT SERVICE LIMPEZA DE BENS IMOVEIS LTDA,JAN/2020,3166.20,"LIQUIDAÇÃO DA NF 3473, REF À FAT NOV/19 DO CON...",'-8

<class 'pandas.DataFrame'>
RangeIndex: 27454 entries, 0 to 27453
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Documento Hábil         23804 non-null  str
 1   DH - Credor             26045 non-null  str
 2   Unnamed: 3              26045 non-null  str
 3   DH - Mês Emissão        26045 non-null  str
 4   DH - Valor              26045 non-null  float64
 5   DH - Observação         26045 non-null  str
 6   DH Item - Nota Empenho  27454 non-null  str
dtypes: float64(1), str(6)
memory usage: 1.5 MB

In [4]:
# renomeando as colunas
dh_semanal_5.rename(columns={
    'Documento Hábil': 'dh_documento_habil',
    'DH - Credor': 'dh_doc_fornecedor',
    'Unnamed: 3': 'dh_nome_fornecedor',
    'DH - Mês Emissão': 'dh_mes_emissao',
    'DH - Valor': 'dh_valor',
    'DH - Observação': 'dh_observacao',
    'DH Item - Nota Empenho': 'dh_empenho'
}, inplace=True)

display(dh_semanal_5.head(2))
dh_semanal_5.info()

,dh_documento_habil,dh_doc_fornecedor,dh_nome_fornecedor,dh_mes_emissao,dh_valor,dh_observacao,dh_empenho
0,110096000012020NP000002,06798516000100,EGEL LOCACAO DE VEICULOS LTDA,JAN/2020,20437.63,LIQUIDAÇÃO DA NF. 5412 DE 04/DEZ/2019 FATURA ...,'-8
1,110096000012020NP000003,15039942000150,STARLIGHT SERVICE LIMPEZA DE BENS IMOVEIS LTDA,JAN/2020,3166.20,"LIQUIDAÇÃO DA NF 3473, REF À FAT NOV/19 DO CON...",'-8

<class 'pandas.DataFrame'>
RangeIndex: 27454 entries, 0 to 27453
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   dh_documento_habil  23804 non-null  str
 1   dh_doc_fornecedor   26045 non-null  str
 2   dh_nome_fornecedor  26045 non-null  str
 3   dh_mes_emissao      26045 non-null  str
 4   dh_valor            26045 non-null  float64
 5   dh_observacao       26045 non-null  str
 6   dh_empenho          27454 non-null  str
dtypes: float64(1), str(6)
memory usage: 1.5 MB

In [5]:
# removendo colunas vazias
dh_semanal_5.dropna(axis=1, how='all', inplace=True)

# removendo linhas inválidas
dh_semanal_5 = dh_semanal_5[dh_semanal_5['dh_documento_habil'].notna()]
dh_semanal_5 = dh_semanal_5[dh_semanal_5['dh_empenho'].notna()]
dh_semanal_5 = dh_semanal_5[dh_semanal_5['dh_empenho'] != "'-8"]

# excluindo os 11 primeiros caracteres da coluna 'dh_documento_habil'
dh_semanal_5['dh_documento_habil'] = dh_semanal_5['dh_documento_habil'].str[11:]
dh_semanal_5['dh_empenho'] = dh_semanal_5['dh_empenho'].str[11:]


display(dh_semanal_5.head(2))
dh_semanal_5.info()

,dh_documento_habil,dh_doc_fornecedor,dh_nome_fornecedor,dh_mes_emissao,dh_valor,dh_observacao,dh_empenho
10274,2022NP000441,12584574000133,JARINALDO AMORIM DE SOUZA,MAR/2022,400.0,LIQUIDAÇÃO PARA PAGAMENTO DA NOTA FISCAL NR 00...,2021NE000320
11171,2022NP001250,12584574000133,JARINALDO AMORIM DE SOUZA,MAI/2022,400.0,LIQUIDAÇÃO PARA PAGAMENTO DA NOTA FISCAL NR 00...,2021NE000320

<class 'pandas.DataFrame'>
Index: 3924 entries, 10274 to 27453
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   dh_documento_habil  3924 non-null   str
 1   dh_doc_fornecedor   3924 non-null   str
 2   dh_nome_fornecedor  3924 non-null   str
 3   dh_mes_emissao      3924 non-null   str
 4   dh_valor            3924 non-null   float64
 5   dh_observacao       3924 non-null   str
 6   dh_empenho          3924 non-null   str
dtypes: float64(1), str(6)
memory usage: 245.2 KB

In [6]:
# removendo duplicados
dh_semanal_5.drop_duplicates(inplace=True)
#dh_semanal_5.drop_duplicates(subset=['dh_chave_relacionamento'], inplace=True)

display(dh_semanal_5.head(2))
dh_semanal_5.info()

,dh_documento_habil,dh_doc_fornecedor,dh_nome_fornecedor,dh_mes_emissao,dh_valor,dh_observacao,dh_empenho
10274,2022NP000441,12584574000133,JARINALDO AMORIM DE SOUZA,MAR/2022,400.0,LIQUIDAÇÃO PARA PAGAMENTO DA NOTA FISCAL NR 00...,2021NE000320
11171,2022NP001250,12584574000133,JARINALDO AMORIM DE SOUZA,MAI/2022,400.0,LIQUIDAÇÃO PARA PAGAMENTO DA NOTA FISCAL NR 00...,2021NE000320

<class 'pandas.DataFrame'>
Index: 3924 entries, 10274 to 27453
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   dh_documento_habil  3924 non-null   str
 1   dh_doc_fornecedor   3924 non-null   str
 2   dh_nome_fornecedor  3924 non-null   str
 3   dh_mes_emissao      3924 non-null   str
 4   dh_valor            3924 non-null   float64
 5   dh_observacao       3924 non-null   str
 6   dh_empenho          3924 non-null   str
dtypes: float64(1), str(6)
memory usage: 245.2 KB

In [7]:
# salvando a base de dados tratada
dh_semanal_5.to_excel('dh_semanal_0.5_tratada.xlsx', sheet_name='DH_semanal_5', index=False)