In [1]:
import pandas as pd
import openpyxl
import numpy as np

In [2]:
# carregando a base de dados
notas_semanal_5 = pd.read_excel('notas_semanal_0.5.xlsx', header=2)

# removendo os espaaços desnecessários da base de dados
notas_semanal_5.columns = notas_semanal_5.columns.str.strip()

display(notas_semanal_5.head(5))
notas_semanal_5.info()

c:\Users\luis.henrique\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,NS - Título Crédito,Favorecido Doc.,Unnamed: 2,NS - Tipo Título Crédito,NS - Inscrição 1,NS - Valor Linha,NS - Mês Valorização,NS - Dia Valorização,Doc - Observação,Título Crédito,Doc - Lançado por,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,'-8,'-8,SEM INFORMACAO,'-8,'-8,0.99,DEZ/2023,31/12/2023,REGISTRO DE ENCERRAMENTO DAS CONTAS DE RESULTA...,'-8,E0182,COORDENACAO GERAL DE CONTAB,170999,16/03/2024
1,NaN,NaN,NaN,NaN,NaN,7.89,DEZ/2023,31/12/2023,REGISTRO DE ENCERRAMENTO DAS CONTAS DE RESULTA...,'-8,E0182,COORDENACAO GERAL DE CONTAB,170999,16/03/2024
2,NaN,NaN,NaN,NaN,NaN,13.60,DEZ/2022,31/12/2022,REGISTRO DE ENCERRAMENTO DAS CONTAS DE RESULTA...,'-8,E0182,COORDENACAO GERAL DE CONTAB,170999,24/01/2023
3,NaN,NaN,NaN,NaN,NaN,35.96,DEZ/2024,31/12/2024,REGISTRO DE ENCERRAMENTO DAS CONTAS DE RESULTA...,'-8,E0182,COORDENACAO GERAL DE CONTAB,170999,21/01/2025
4,NaN,NaN,NaN,NaN,NaN,44.62,DEZ/2024,31/12/2024,REGISTRO DE ENCERRAMENTO DAS CONTAS DE RESULTA...,'-8,E0182,COORDENACAO GERAL DE CONTAB,170999,21/01/2025

<class 'pandas.DataFrame'>
RangeIndex: 57841 entries, 0 to 57840
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   NS - Título Crédito       15667 non-null  str
 1   Favorecido Doc.           15667 non-null  str
 2   Unnamed: 2                15667 non-null  str
 3   NS - Tipo Título Crédito  15667 non-null  str
 4   NS - Inscrição 1          30558 non-null  str
 5   NS - Valor Linha          56995 non-null  float64
 6   NS - Mês Valorização      57180 non-null  str
 7   NS - Dia Valorização      57434 non-null  str
 8   Doc - Observação          57840 non-null  str
 9   Título Crédito            57840 non-null  str
 10  Doc - Lançado por         57841 non-null  str
 11  Unnamed: 11               57841 non-null  str
 12  Unnamed: 12               57841 non-null  int64
 13  Unnamed: 13               57841 non-null  str
dtypes: float64(1), int64(1), str(12)
memory usage: 6.2 MB

In [3]:
# excluido colunas desncessárias
notas_semanal_5.drop(columns=['NS - Tipo Título Crédito', 'NS - Valor Linha', 'NS - Inscrição 1', 'Unnamed: 13', 'Doc - Lançado por', 'Título Crédito'], inplace=True)

display(notas_semanal_5.head(5))
notas_semanal_5.info()

,NS - Título Crédito,Favorecido Doc.,Unnamed: 2,NS - Mês Valorização,NS - Dia Valorização,Doc - Observação,Unnamed: 11,Unnamed: 12
0,'-8,'-8,SEM INFORMACAO,DEZ/2023,31/12/2023,REGISTRO DE ENCERRAMENTO DAS CONTAS DE RESULTA...,COORDENACAO GERAL DE CONTAB,170999
1,NaN,NaN,NaN,DEZ/2023,31/12/2023,REGISTRO DE ENCERRAMENTO DAS CONTAS DE RESULTA...,COORDENACAO GERAL DE CONTAB,170999
2,NaN,NaN,NaN,DEZ/2022,31/12/2022,REGISTRO DE ENCERRAMENTO DAS CONTAS DE RESULTA...,COORDENACAO GERAL DE CONTAB,170999
3,NaN,NaN,NaN,DEZ/2024,31/12/2024,REGISTRO DE ENCERRAMENTO DAS CONTAS DE RESULTA...,COORDENACAO GERAL DE CONTAB,170999
4,NaN,NaN,NaN,DEZ/2024,31/12/2024,REGISTRO DE ENCERRAMENTO DAS CONTAS DE RESULTA...,COORDENACAO GERAL DE CONTAB,170999

<class 'pandas.DataFrame'>
RangeIndex: 57841 entries, 0 to 57840
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   NS - Título Crédito   15667 non-null  str
 1   Favorecido Doc.       15667 non-null  str
 2   Unnamed: 2            15667 non-null  str
 3   NS - Mês Valorização  57180 non-null  str
 4   NS - Dia Valorização  57434 non-null  str
 5   Doc - Observação      57840 non-null  str
 6   Unnamed: 11           57841 non-null  str
 7   Unnamed: 12           57841 non-null  int64
dtypes: int64(1), str(7)
memory usage: 3.5 MB

In [4]:
# renomeando as colunas
notas_semanal_5.rename(columns={
    'NS - Título Crédito': 'notas_documento_habil',
    'Favorecido Doc.': 'notas_doc_fornecedor',
    'Unnamed: 2': 'notas_nome_fornecedor',
    # 'NS - Inscrição 1': 'notas_empenho',
    'NS - Mês Valorização': 'notas_mes_valorizacao',
    'NS - Dia Valorização': 'notas_data_valorizacao',
    'Doc - Observação': 'notas_doc_observacao',
    'Título Crédito': 'notas_empenho',
    'Doc - Lançado por': 'notas_id_setor',
    'Unnamed: 11': 'notas_nome_servidor',
    'Unnamed: 12': 'notas_cod_servidor'
    #'Unnamed: 13': 'notas_nome_servidor',
}, inplace=True)

display(notas_semanal_5.head(5))
notas_semanal_5.info()

,notas_documento_habil,notas_doc_fornecedor,notas_nome_fornecedor,notas_mes_valorizacao,notas_data_valorizacao,notas_doc_observacao,notas_nome_servidor,notas_cod_servidor
0,'-8,'-8,SEM INFORMACAO,DEZ/2023,31/12/2023,REGISTRO DE ENCERRAMENTO DAS CONTAS DE RESULTA...,COORDENACAO GERAL DE CONTAB,170999
1,NaN,NaN,NaN,DEZ/2023,31/12/2023,REGISTRO DE ENCERRAMENTO DAS CONTAS DE RESULTA...,COORDENACAO GERAL DE CONTAB,170999
2,NaN,NaN,NaN,DEZ/2022,31/12/2022,REGISTRO DE ENCERRAMENTO DAS CONTAS DE RESULTA...,COORDENACAO GERAL DE CONTAB,170999
3,NaN,NaN,NaN,DEZ/2024,31/12/2024,REGISTRO DE ENCERRAMENTO DAS CONTAS DE RESULTA...,COORDENACAO GERAL DE CONTAB,170999
4,NaN,NaN,NaN,DEZ/2024,31/12/2024,REGISTRO DE ENCERRAMENTO DAS CONTAS DE RESULTA...,COORDENACAO GERAL DE CONTAB,170999

<class 'pandas.DataFrame'>
RangeIndex: 57841 entries, 0 to 57840
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   notas_documento_habil   15667 non-null  str
 1   notas_doc_fornecedor    15667 non-null  str
 2   notas_nome_fornecedor   15667 non-null  str
 3   notas_mes_valorizacao   57180 non-null  str
 4   notas_data_valorizacao  57434 non-null  str
 5   notas_doc_observacao    57840 non-null  str
 6   notas_nome_servidor     57841 non-null  str
 7   notas_cod_servidor      57841 non-null  int64
dtypes: int64(1), str(7)
memory usage: 3.5 MB

In [5]:
# removendo colunas vazias
notas_semanal_5.dropna(axis=1, how='all', inplace=True)

# removendo linhas inválidas
notas_semanal_5 = notas_semanal_5[notas_semanal_5['notas_documento_habil'].notna()]
notas_semanal_5 = notas_semanal_5[notas_semanal_5['notas_documento_habil'] != "'-8"]
#notas_semanal_5 = notas_semanal_5[notas_semanal_5['notas_empenho'].notna()]
#notas_semanal_5 = notas_semanal_5[notas_semanal_5['notas_empenho'] != "'-8"]

# excluindo os 11 primeiros caracteres da coluna 'notas_documento_habil'
# notas_semanal_5['notas_documento_habil'] = notas_semanal_5['notas_documento_habil'].str[11:]
# notas_semanal_5['notas_empenho'] = notas_semanal_5['notas_empenho'].str[11:]

# converter a coluna 'notas_data_valorizacao' para o formato datetime
notas_semanal_5['notas_data_valorizacao'] = pd.to_datetime(notas_semanal_5['notas_data_valorizacao'], errors='coerce')

display(notas_semanal_5.head(5))
notas_semanal_5.info()

C:\Users\luis.henrique\AppData\Local\Temp\ipykernel_23312\907207518.py:15: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  notas_semanal_5['notas_data_valorizacao'] = pd.to_datetime(notas_semanal_5['notas_data_valorizacao'], errors='coerce')

,notas_documento_habil,notas_doc_fornecedor,notas_nome_fornecedor,notas_mes_valorizacao,notas_data_valorizacao,notas_doc_observacao,notas_nome_servidor,notas_cod_servidor
104,2022DB000001,13100722000160,BAHIA TRIBUNAL DE JUSTICA,MAI/2022,2022-05-20,REGULARIZACAO DO CANCELAMENTO PELO BANCO DO BR...,ANA GLORIA RABELO VIANA DA COSTA,110096
109,2022DB000002,13100722000160,BAHIA TRIBUNAL DE JUSTICA,NOV/2022,2022-11-28,REGULARIZACAO DO CANCELAMENTO PELO BANCO DO BR...,ANA GLORIA RABELO VIANA DA COSTA,110096
114,2022DD000001,19362299000152,ERICA E.G. LIMA SERVICOS DE MAO DE OBRA LTDA,JUL/2022,2022-07-27,"DEVOLUCAO POR GRU DO VALOR R$ 7.747,25, RELATI...",ALTAIR FERREIRA SANGUINETTE DE ARAUJO,110096
118,2022NP000001,02558157000162,TELEFONICA BRASIL S.A.,JAN/2022,2022-01-07,LIQUIDACAO DA FATURA 1200116559747 REFERENTE...,SONIA MARIA CAVALCANTI C. D,110096
121,2022NP000002,02558157000162,TELEFONICA BRASIL S.A.,JAN/2022,2022-01-07,LIQUIDACAO DA FATURA 1200116559781 REFERENTE...,SONIA MARIA CAVALCANTI C. D,110096

<class 'pandas.DataFrame'>
Index: 15666 entries, 104 to 57829
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   notas_documento_habil   15666 non-null  str
 1   notas_doc_fornecedor    15666 non-null  str
 2   notas_nome_fornecedor   15666 non-null  str
 3   notas_mes_valorizacao   15666 non-null  str
 4   notas_data_valorizacao  15666 non-null  datetime64[us]
 5   notas_doc_observacao    15666 non-null  str
 6   notas_nome_servidor     15666 non-null  str
 7   notas_cod_servidor      15666 non-null  int64
dtypes: datetime64[us](1), int64(1), str(6)
memory usage: 1.1 MB

In [6]:
# criando chave de relacionamento
#notas_semanal_5['notas_chave_relacionamento'] = notas_semanal_5['notas_documento_habil'].astype(str) + '_' + notas_semanal_5['notas_doc_fornecedor'].astype(str)

In [7]:
# removendo duplicados
notas_semanal_5.drop_duplicates(inplace=True)
#notas_semanal_5.drop_duplicates(subset=['notas_chave_relacionamento'], inplace=True)

display(notas_semanal_5.head(10))
notas_semanal_5.info()

,notas_documento_habil,notas_doc_fornecedor,notas_nome_fornecedor,notas_mes_valorizacao,notas_data_valorizacao,notas_doc_observacao,notas_nome_servidor,notas_cod_servidor
104,2022DB000001,13100722000160,BAHIA TRIBUNAL DE JUSTICA,MAI/2022,2022-05-20,REGULARIZACAO DO CANCELAMENTO PELO BANCO DO BR...,ANA GLORIA RABELO VIANA DA COSTA,110096
109,2022DB000002,13100722000160,BAHIA TRIBUNAL DE JUSTICA,NOV/2022,2022-11-28,REGULARIZACAO DO CANCELAMENTO PELO BANCO DO BR...,ANA GLORIA RABELO VIANA DA COSTA,110096
114,2022DD000001,19362299000152,ERICA E.G. LIMA SERVICOS DE MAO DE OBRA LTDA,JUL/2022,2022-07-27,"DEVOLUCAO POR GRU DO VALOR R$ 7.747,25, RELATI...",ALTAIR FERREIRA SANGUINETTE DE ARAUJO,110096
118,2022NP000001,02558157000162,TELEFONICA BRASIL S.A.,JAN/2022,2022-01-07,LIQUIDACAO DA FATURA 1200116559747 REFERENTE...,SONIA MARIA CAVALCANTI C. D,110096
121,2022NP000002,02558157000162,TELEFONICA BRASIL S.A.,JAN/2022,2022-01-07,LIQUIDACAO DA FATURA 1200116559781 REFERENTE...,SONIA MARIA CAVALCANTI C. D,110096
124,2022NP000003,02558157000162,TELEFONICA BRASIL S.A.,JAN/2022,2022-01-07,PSF/CGE-PB - PROCESSO 00654.00O164/2021-85 - S...,SONIA MARIA CAVALCANTI C. D,110096
127,2022NP000004,02558157000162,TELEFONICA BRASIL S.A.,JAN/2022,2022-01-07,LIQUIDACAO DA FATURA 1100040217039 REFERENTE ...,SONIA MARIA CAVALCANTI C. D,110096
130,2022NP000005,08247960000162,REAL JG FACILITIES S/A,JAN/2022,2022-01-10,"LIQ. DA NF. 13303 DE 30/12/2021, REF. DIFERENC...",ALTAIR FERREIRA SANGUINETTE DE ARAUJO,110096
136,2022NP000006,15150504000165,LDS SERVICOS DE LIMPEZA LTDA,JAN/2022,2022-01-10,"LIQ. DA NF. 7773 DE 16/12/2021, FATURA REF. FA...",ALTAIR FERREIRA SANGUINETTE DE ARAUJO,110096
144,2022NP000007,15150504000165,LDS SERVICOS DE LIMPEZA LTDA,JAN/2022,2022-01-10,"LIQ. DA NF. 7772 DE 16/12/2021, FATURA REF. ( ...",ALTAIR FERREIRA SANGUINETTE DE ARAUJO,110096

<class 'pandas.DataFrame'>
Index: 15666 entries, 104 to 57829
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   notas_documento_habil   15666 non-null  str
 1   notas_doc_fornecedor    15666 non-null  str
 2   notas_nome_fornecedor   15666 non-null  str
 3   notas_mes_valorizacao   15666 non-null  str
 4   notas_data_valorizacao  15666 non-null  datetime64[us]
 5   notas_doc_observacao    15666 non-null  str
 6   notas_nome_servidor     15666 non-null  str
 7   notas_cod_servidor      15666 non-null  int64
dtypes: datetime64[us](1), int64(1), str(6)
memory usage: 1.1 MB

In [8]:
# salvando a base de dados tratada
notas_semanal_5.to_excel('notas_semanal_0.5_tratada.xlsx', sheet_name='Notas_semanal_5', index=False)