In [1]:
import pandas as pd
import openpyxl
import numpy as np
import datetime

In [2]:
# carregando a base de dados
ob_semanal_5 = pd.read_excel('ob_semanal_0.5.xlsx', header=2)

# removendo os espaaços desnecessários da base de dados
ob_semanal_5.columns = ob_semanal_5.columns.str.strip()

display(ob_semanal_5.head(2))
ob_semanal_5.info()

c:\Users\luis.henrique\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Documento Hábil,Compr. - Dia Pagamento,Emissão - Mês,OB,Favorecido Doc.,Unnamed: 5,OB - Processo,Doc - Observação,Doc - Valor,OB - Evento,Unnamed: 10,OB - Inscrição 1
0,110096000012018NP002325,23/03/2020,MAR/2020,110096000012020OB801172,04529815000113,CONSTRUTORA SALTECH LTDA,00490.000666/2016-69,"PAGAMENTO DA NOTA FISCAL 1157, 03/09/2019, NO ...","130174,45",531814.0,PGTO CONTAS A PAGAR/FORNECEDOR,2016NE802030
1,110096000012018NP003946,24/02/2022,FEV/2022,110096000012022OB800369,00000000000191,BANCO DO BRASIL SA,00587.000512/2018-60,PAGT. REF. PROCESSO 5000806-80.2019.8.13.0701 ...,"36718,41",531814.0,PGTO CONTAS A PAGAR/FORNECEDOR,2017NE801935

<class 'pandas.DataFrame'>
RangeIndex: 29055 entries, 0 to 29054
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Documento Hábil         23476 non-null  str
 1   Compr. - Dia Pagamento  23966 non-null  str
 2   Emissão - Mês           24264 non-null  str
 3   OB                      25776 non-null  str
 4   Favorecido Doc.         25776 non-null  str
 5   Unnamed: 5              25776 non-null  str
 6   OB - Processo           25776 non-null  str
 7   Doc - Observação        25776 non-null  str
 8   Doc - Valor             25776 non-null  str
 9   OB - Evento             25776 non-null  float64
 10  Unnamed: 10             25776 non-null  str
 11  OB - Inscrição 1        29055 non-null  str
dtypes: float64(1), str(11)
memory usage: 2.7 MB

In [3]:
# excluindo colunas desnecessárias
ob_semanal_5.drop(columns=['Unnamed: 10'], inplace=True)

display(ob_semanal_5.head(2))
ob_semanal_5.info()

,Documento Hábil,Compr. - Dia Pagamento,Emissão - Mês,OB,Favorecido Doc.,Unnamed: 5,OB - Processo,Doc - Observação,Doc - Valor,OB - Evento,OB - Inscrição 1
0,110096000012018NP002325,23/03/2020,MAR/2020,110096000012020OB801172,04529815000113,CONSTRUTORA SALTECH LTDA,00490.000666/2016-69,"PAGAMENTO DA NOTA FISCAL 1157, 03/09/2019, NO ...","130174,45",531814.0,2016NE802030
1,110096000012018NP003946,24/02/2022,FEV/2022,110096000012022OB800369,00000000000191,BANCO DO BRASIL SA,00587.000512/2018-60,PAGT. REF. PROCESSO 5000806-80.2019.8.13.0701 ...,"36718,41",531814.0,2017NE801935

<class 'pandas.DataFrame'>
RangeIndex: 29055 entries, 0 to 29054
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Documento Hábil         23476 non-null  str
 1   Compr. - Dia Pagamento  23966 non-null  str
 2   Emissão - Mês           24264 non-null  str
 3   OB                      25776 non-null  str
 4   Favorecido Doc.         25776 non-null  str
 5   Unnamed: 5              25776 non-null  str
 6   OB - Processo           25776 non-null  str
 7   Doc - Observação        25776 non-null  str
 8   Doc - Valor             25776 non-null  str
 9   OB - Evento             25776 non-null  float64
 10  OB - Inscrição 1        29055 non-null  str
dtypes: float64(1), str(10)
memory usage: 2.4 MB

In [4]:
ob_semanal_5.rename(columns = {
    'Documento Hábil': 'ob_documento_habil',
    'Compr. - Dia Pagamento': 'ob_data_pagamento',
    'Emissão - Mês': 'ob_mes_emissao',
    'OB': 'ob_ordem_pagamento',
    'Favorecido Doc.': 'ob_doc_fornecedor',
    'Unnamed: 5': 'ob_nome_fornecedor',
    'OB - Processo': 'ob_processo',
    'Doc - Observação': 'ob_observacao',
    'Doc - Valor': 'ob_valor',
    'OB - Evento': 'ob_evento',
    'OB - Inscrição 1': 'ob_empenho',

}, inplace=True)

display(ob_semanal_5.head(5))
ob_semanal_5.info()

,ob_documento_habil,ob_data_pagamento,ob_mes_emissao,ob_ordem_pagamento,ob_doc_fornecedor,ob_nome_fornecedor,ob_processo,ob_observacao,ob_valor,ob_evento,ob_empenho
0,110096000012018NP002325,23/03/2020,MAR/2020,110096000012020OB801172,04529815000113,CONSTRUTORA SALTECH LTDA,00490.000666/2016-69,"PAGAMENTO DA NOTA FISCAL 1157, 03/09/2019, NO ...","130174,45",531814.0,2016NE802030
1,110096000012018NP003946,24/02/2022,FEV/2022,110096000012022OB800369,00000000000191,BANCO DO BRASIL SA,00587.000512/2018-60,PAGT. REF. PROCESSO 5000806-80.2019.8.13.0701 ...,"36718,41",531814.0,2017NE801935
2,110096000012018NP003949,24/02/2022,FEV/2022,110096000012022OB800368,00000000000191,BANCO DO BRASIL SA,00587.000512/2018-60,PAGT. REF. PROCESSO 5000806-80.2019.8.13.0701 ...,"11939,62",531814.0,2017NE801931
3,110096000012019NP000047,24/02/2022,FEV/2022,110096000012022OB800366,00000000000191,BANCO DO BRASIL SA,00587.000512/2018-60,PAGT. REF. PROCESSO 5000806-80.2019.8.13.0701 ...,"29374,72",531814.0,2017NE802249
4,110096000012019NP000049,24/02/2022,FEV/2022,110096000012022OB800370,00000000000191,BANCO DO BRASIL SA,00587.000512/2018-60,PAGT. REF. PROCESSO 5000806-80.2019.8.13.0701 ...,"115700,75",531814.0,2017NE801926

<class 'pandas.DataFrame'>
RangeIndex: 29055 entries, 0 to 29054
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ob_documento_habil  23476 non-null  str
 1   ob_data_pagamento   23966 non-null  str
 2   ob_mes_emissao      24264 non-null  str
 3   ob_ordem_pagamento  25776 non-null  str
 4   ob_doc_fornecedor   25776 non-null  str
 5   ob_nome_fornecedor  25776 non-null  str
 6   ob_processo         25776 non-null  str
 7   ob_observacao       25776 non-null  str
 8   ob_valor            25776 non-null  str
 9   ob_evento           25776 non-null  float64
 10  ob_empenho          29055 non-null  str
dtypes: float64(1), str(10)
memory usage: 2.4 MB

In [5]:
# removendo colunas vazias
ob_semanal_5.dropna(axis=1, how='all', inplace=True)

# removendo linhas inválidas
ob_semanal_5 = ob_semanal_5[ob_semanal_5['ob_documento_habil'].notna()]
ob_semanal_5 = ob_semanal_5[ob_semanal_5['ob_documento_habil'] != "'-8"]
ob_semanal_5 = ob_semanal_5[ob_semanal_5['ob_empenho'].notna()]
ob_semanal_5 = ob_semanal_5[ob_semanal_5['ob_empenho'] != "'-8"]

# excluindo os 11 primeiros caracteres da coluna 'ob_documento_habil'
ob_semanal_5['ob_documento_habil'] = ob_semanal_5['ob_documento_habil'].str[11:]
#ob_semanal_5['ob_empenho'] = ob_semanal_5['ob_empenho'].str[11:]

# converter a coluna 'ob_data_pagamento' para o formato datetime
ob_semanal_5['ob_data_pagamento'] = pd.to_datetime(ob_semanal_5['ob_data_pagamento'], errors='coerce')

# convertendo a coluna 'ob_evento' para string
ob_semanal_5['ob_evento'] = ob_semanal_5['ob_evento'].astype(str)

# convertendo a coluna 'ob_valor' para tipo float
ob_semanal_5['ob_valor'] = pd.to_numeric(
    ob_semanal_5['ob_valor']
    .astype(str)
    .str.replace('R$', '', regex=False)
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
    .str.strip(),
    errors='coerce'
)

display(ob_semanal_5.head(2))
ob_semanal_5.info()

C:\Users\luis.henrique\AppData\Local\Temp\ipykernel_24988\3765385009.py:15: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  ob_semanal_5['ob_data_pagamento'] = pd.to_datetime(ob_semanal_5['ob_data_pagamento'], errors='coerce')

,ob_documento_habil,ob_data_pagamento,ob_mes_emissao,ob_ordem_pagamento,ob_doc_fornecedor,ob_nome_fornecedor,ob_processo,ob_observacao,ob_valor,ob_evento,ob_empenho
0,2018NP002325,2020-03-23,MAR/2020,110096000012020OB801172,04529815000113,CONSTRUTORA SALTECH LTDA,00490.000666/2016-69,"PAGAMENTO DA NOTA FISCAL 1157, 03/09/2019, NO ...",130174.45,531814.0,2016NE802030
1,2018NP003946,2022-02-24,FEV/2022,110096000012022OB800369,00000000000191,BANCO DO BRASIL SA,00587.000512/2018-60,PAGT. REF. PROCESSO 5000806-80.2019.8.13.0701 ...,36718.41,531814.0,2017NE801935

<class 'pandas.DataFrame'>
Index: 23476 entries, 0 to 29054
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ob_documento_habil  23476 non-null  str
 1   ob_data_pagamento   23476 non-null  datetime64[us]
 2   ob_mes_emissao      23476 non-null  str
 3   ob_ordem_pagamento  23476 non-null  str
 4   ob_doc_fornecedor   23476 non-null  str
 5   ob_nome_fornecedor  23476 non-null  str
 6   ob_processo         23476 non-null  str
 7   ob_observacao       23476 non-null  str
 8   ob_valor            23476 non-null  float64
 9   ob_evento           23476 non-null  str
 10  ob_empenho          23476 non-null  str
dtypes: datetime64[us](1), float64(1), str(9)
memory usage: 2.1 MB

In [6]:
# removendo duplicados
ob_semanal_5.drop_duplicates(inplace=True)
#ob_semanal_5.drop_duplicates(subset=['dh_chave_relacionamento'], inplace=True)

display(ob_semanal_5.head(2))
ob_semanal_5.info()

,ob_documento_habil,ob_data_pagamento,ob_mes_emissao,ob_ordem_pagamento,ob_doc_fornecedor,ob_nome_fornecedor,ob_processo,ob_observacao,ob_valor,ob_evento,ob_empenho
0,2018NP002325,2020-03-23,MAR/2020,110096000012020OB801172,04529815000113,CONSTRUTORA SALTECH LTDA,00490.000666/2016-69,"PAGAMENTO DA NOTA FISCAL 1157, 03/09/2019, NO ...",130174.45,531814.0,2016NE802030
1,2018NP003946,2022-02-24,FEV/2022,110096000012022OB800369,00000000000191,BANCO DO BRASIL SA,00587.000512/2018-60,PAGT. REF. PROCESSO 5000806-80.2019.8.13.0701 ...,36718.41,531814.0,2017NE801935

<class 'pandas.DataFrame'>
Index: 23476 entries, 0 to 29054
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ob_documento_habil  23476 non-null  str
 1   ob_data_pagamento   23476 non-null  datetime64[us]
 2   ob_mes_emissao      23476 non-null  str
 3   ob_ordem_pagamento  23476 non-null  str
 4   ob_doc_fornecedor   23476 non-null  str
 5   ob_nome_fornecedor  23476 non-null  str
 6   ob_processo         23476 non-null  str
 7   ob_observacao       23476 non-null  str
 8   ob_valor            23476 non-null  float64
 9   ob_evento           23476 non-null  str
 10  ob_empenho          23476 non-null  str
dtypes: datetime64[us](1), float64(1), str(9)
memory usage: 2.1 MB

In [7]:
#ob_semanal_5 = ob_semanal_5[ob_semanal_5['ob_empenho'].astype(str).str.startswith(('2023','2024', '2025', '2026'), na=False)]
ob_semanal_5.info()

<class 'pandas.DataFrame'>
Index: 23476 entries, 0 to 29054
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ob_documento_habil  23476 non-null  str
 1   ob_data_pagamento   23476 non-null  datetime64[us]
 2   ob_mes_emissao      23476 non-null  str
 3   ob_ordem_pagamento  23476 non-null  str
 4   ob_doc_fornecedor   23476 non-null  str
 5   ob_nome_fornecedor  23476 non-null  str
 6   ob_processo         23476 non-null  str
 7   ob_observacao       23476 non-null  str
 8   ob_valor            23476 non-null  float64
 9   ob_evento           23476 non-null  str
 10  ob_empenho          23476 non-null  str
dtypes: datetime64[us](1), float64(1), str(9)
memory usage: 2.1 MB

In [8]:
# salvando a base de dados tratada
ob_semanal_5.to_excel('ob_semanal_0.5_tratada.xlsx', sheet_name='OB_semanal_5', index=False)